#pragma once

enum class MusicSong : uint8_t {
    MainTheme
};

enum class MusicSFX : uint8_t {
    SFX_Death,
    SFX_Victory,
    SFX_XPGain,
    SFX_Three_Inc,
    SFX_Three_Dec,
    SFX_PlayerBlip,
    SFX_EnemyBlip,
    SFX_Explosion,
    SFX_DoubleBeep,
    SFX_DoubleBeepDown,
    SFX_Bet1,
    SFX_Bet2,
    SFX_Bet3,
    SFX_Bet4,
    SFX_Bet5,
    SFX_Bet6,
    SFX_Click,
    SFX_SmallBlind,
    SFX_BigBlind,
};


enum class Direction : uint8_t {
    Backward,
    Right,
    Forward,
    Left,
    None,
};

enum class ItemType : uint8_t {
    Key1 = 50,
    WoodenBarrier,
    TrapDoor,
    Punji,
    Hammer,
    Puff,
    None = 99,
};


enum class ItemAction : uint8_t {
    None,
    Remove,
    Remove_AddToInventory,
};


enum Stance : uint16_t {

    Man_Start,

        Man_BK_Start = Man_Start,

            Man_Walk_BK_01 = Man_BK_Start,
            Man_Walk_BK_02,
            Man_Walk_BK_03,
            Man_Walk_BK_04,
            
            Man_StandingJump_BK_01,
            Man_StandingJump_BK_02,
            Man_StandingJump_BK_03,
            Man_StandingJump_BK_04,
            Man_StandingJump_BK_05,
            Man_StandingJump_BK_06,
            Man_StandingJump_BK_07,

            Man_StandingJump_BK_UP_01,     // Jump Up
            Man_StandingJump_BK_UP_02,
            Man_StandingJump_BK_UP_03,
            Man_StandingJump_BK_UP_04,
            Man_StandingJump_BK_UP_05,
            Man_StandingJump_BK_UP_06,

            Man_ClimbLadder_BK_RH_UP_01,
            Man_ClimbLadder_BK_RH_UP_02,
            Man_ClimbLadder_BK_RH_UP_03,
            Man_ClimbLadder_BK_RH_UP_04,
            Man_ClimbLadder_BK_RH_UP_05,
            Man_ClimbLadder_BK_RH_UP_06,
            Man_ClimbLadder_BK_RH_UP_07,
            Man_ClimbLadder_BK_RH_UP_08,
            Man_ClimbLadder_BK_RH_UP_09,
            Man_ClimbLadder_BK_RH_UP_10,
            Man_ClimbLadder_BK_RH_UP_11,
            Man_ClimbLadder_BK_RH_UP_12,
            Man_ClimbLadder_BK_RH_UP_13,
            Man_ClimbLadder_BK_RH_UP_14,

            Man_ClimbLadder_BK_RH_DOWN_01,
            Man_ClimbLadder_BK_RH_DOWN_02,
            Man_ClimbLadder_BK_RH_DOWN_03,
            Man_ClimbLadder_BK_RH_DOWN_04,
            Man_ClimbLadder_BK_RH_DOWN_05,
            Man_ClimbLadder_BK_RH_DOWN_06,
            Man_ClimbLadder_BK_RH_DOWN_07,
            Man_ClimbLadder_BK_RH_DOWN_08,
            Man_ClimbLadder_BK_RH_DOWN_09,
            Man_ClimbLadder_BK_RH_DOWN_10,
            Man_ClimbLadder_BK_RH_DOWN_11,
            Man_ClimbLadder_BK_RH_DOWN_12,
            Man_ClimbLadder_BK_RH_DOWN_13,
            Man_ClimbLadder_BK_RH_DOWN_14,

            Man_ClimbLadder_BK_LH_UP_01,
            Man_ClimbLadder_BK_LH_UP_02,
            Man_ClimbLadder_BK_LH_UP_03,
            Man_ClimbLadder_BK_LH_UP_04,
            Man_ClimbLadder_BK_LH_UP_05,
            Man_ClimbLadder_BK_LH_UP_06,
            Man_ClimbLadder_BK_LH_UP_07,
            Man_ClimbLadder_BK_LH_UP_08,
            Man_ClimbLadder_BK_LH_UP_09,
            Man_ClimbLadder_BK_LH_UP_10,
            Man_ClimbLadder_BK_LH_UP_11,
            Man_ClimbLadder_BK_LH_UP_12,
            Man_ClimbLadder_BK_LH_UP_13,
            Man_ClimbLadder_BK_LH_UP_14,

            Man_ClimbLadder_BK_LH_DOWN_01,
            Man_ClimbLadder_BK_LH_DOWN_02,
            Man_ClimbLadder_BK_LH_DOWN_03,
            Man_ClimbLadder_BK_LH_DOWN_04,
            Man_ClimbLadder_BK_LH_DOWN_05,
            Man_ClimbLadder_BK_LH_DOWN_06,
            Man_ClimbLadder_BK_LH_DOWN_07,
            Man_ClimbLadder_BK_LH_DOWN_08,
            Man_ClimbLadder_BK_LH_DOWN_09,
            Man_ClimbLadder_BK_LH_DOWN_10,
            Man_ClimbLadder_BK_LH_DOWN_11,
            Man_ClimbLadder_BK_LH_DOWN_12,
            Man_ClimbLadder_BK_LH_DOWN_13,
            Man_ClimbLadder_BK_LH_DOWN_14,

            Man_Walk_FallMore_BK_01,
            Man_Walk_FallMore_BK_02,

            Man_Walk_FallLand_BK_01,
            Man_Walk_FallLand_BK_02,
            Man_Walk_FallLand_BK_03,
            Man_Walk_FallLand_BK_04,

            Man_Walk_FallLandSpring_BK_01,
            Man_Walk_FallLandSpring_BK_02,
            Man_Walk_FallLandSpring_BK_03,
            Man_Walk_FallLandSpring_BK_04,
            Man_Walk_FallLandSpring_BK_05,
            Man_Walk_FallLandSpring_BK_06,
            Man_Walk_FallLandSpring_BK_07,
            Man_Walk_FallLandSpring_BK_08,
            Man_Walk_FallLandSpring_BK_09,
            Man_Walk_FallLandSpring_BK_10,
            Man_Walk_FallLandSpring_BK_11,
            Man_Walk_FallLandSpring_BK_12,
            Man_Walk_FallLandSpring_BK_13,
            Man_Walk_FallLandSpring_BK_14,
            Man_Walk_FallLandSpring_BK_15,
            Man_Walk_FallLandSpring_BK_16,
            Man_Walk_FallLandSpring_BK_17,
            Man_Walk_FallLandSpring_BK_18,
            Man_Walk_FallLandSpring_BK_19,
            Man_Walk_FallLandSpring_BK_20,
            Man_Walk_FallLandSpring_BK_21,
            Man_Walk_FallLandSpring_BK_22,
            Man_Walk_FallLandSpring_BK_23,
            Man_Walk_FallLandSpring_BK_24,
            Man_Walk_FallLandSpring_BK_25,
            Man_Walk_FallLandSpring_BK_26,
            Man_Walk_FallLandSpring_BK_27,
            Man_Walk_FallLandSpring_BK_28,

        Man_BK_End = Man_Walk_FallLandSpring_BK_28,
        
        Man_RH_Start,

            Man_Walk_RH_00 = Man_RH_Start,                 // No movement
            Man_Walk_RH_01,
            Man_Walk_RH_02,
            Man_Walk_RH_03,
            Man_Walk_RH_04,

            Man_ClimbStairs_RH_01,
            Man_ClimbStairs_RH_02,
            Man_ClimbStairs_RH_03,
            Man_ClimbStairs_RH_04,
            Man_ClimbStairs_RH_05,
            Man_ClimbStairs_RH_06,
            Man_ClimbStairs_RH_07,
            Man_ClimbStairs_RH_08,

            Man_ClimbStairs_RH_Half_01,
            Man_ClimbStairs_RH_Half_02,
            Man_ClimbStairs_RH_Half_03,
            Man_ClimbStairs_RH_Half_04,

            Man_DescendStairs_RH_01,
            Man_DescendStairs_RH_02,
            Man_DescendStairs_RH_03,
            Man_DescendStairs_RH_04,
            Man_DescendStairs_RH_05,
            Man_DescendStairs_RH_06,
            Man_DescendStairs_RH_07,
            Man_DescendStairs_RH_08,

            Man_DescendStairs_RH_Half_01,
            Man_DescendStairs_RH_Half_02,
            Man_DescendStairs_RH_Half_03,
            Man_DescendStairs_RH_Half_04,

            Man_Walk_FallDown_RH_01,
            Man_Walk_FallDown_RH_02,
            Man_Walk_FallDown_RH_03,
            Man_Walk_FallDown_RH_04,
            Man_Walk_FallDown_RH_05,
            Man_Walk_FallDown_RH_06,

            Man_Walk_FallMore_RH_01,
            Man_Walk_FallMore_RH_02,

            Man_Walk_FallLand_RH_01,
            Man_Walk_FallLand_RH_02,
            Man_Walk_FallLand_RH_03,
            Man_Walk_FallLand_RH_04,

            Man_StandingJump_RH_01,
            Man_StandingJump_RH_02,
            Man_StandingJump_RH_03,
            Man_StandingJump_RH_04,
            Man_StandingJump_RH_05,
            Man_StandingJump_RH_06,
            Man_StandingJump_RH_07,
            
            Man_StandingJump_Small_RH_01,
            Man_StandingJump_Small_RH_02,
            Man_StandingJump_Small_RH_03,

            Man_StandingJump_RH_UP_01,     // Jump Up
            Man_StandingJump_RH_UP_02,
            Man_StandingJump_RH_UP_03,
            Man_StandingJump_RH_UP_04,
            Man_StandingJump_RH_UP_05,
            Man_StandingJump_RH_UP_06,
                    
            Man_StandingJump_RH_UPandOver_01,     // Jump Up
            Man_StandingJump_RH_UPandOver_02,
            Man_StandingJump_RH_UPandOver_03,
            Man_StandingJump_RH_UPandOver_04,
            Man_StandingJump_RH_UPandOver_05,
            Man_StandingJump_RH_UPandOver_06,
            
            Man_WalkingJump_RH_01,
            Man_WalkingJump_RH_02,
            Man_WalkingJump_RH_03,
            Man_WalkingJump_RH_04,
            Man_WalkingJump_RH_05,
            Man_WalkingJump_RH_06,
            Man_WalkingJump_RH_07,
            Man_WalkingJump_RH_08,

            Man_WalkingJump_RH_2_01,
            Man_WalkingJump_RH_2_02,
            Man_WalkingJump_RH_2_03,
            Man_WalkingJump_RH_2_04,
            Man_WalkingJump_RH_2_05,
            Man_WalkingJump_RH_2_06,
            Man_WalkingJump_RH_2_07,
            Man_WalkingJump_RH_2_08,

            Man_WalkingJump_RH_25_01,
            Man_WalkingJump_RH_25_02,
            Man_WalkingJump_RH_25_03,
            Man_WalkingJump_RH_25_04,
            Man_WalkingJump_RH_25_05,
            Man_WalkingJump_RH_25_06,
            Man_WalkingJump_RH_25_07,
            Man_WalkingJump_RH_25_08,
            Man_WalkingJump_RH_25_09,
            Man_WalkingJump_RH_25_10,
            Man_WalkingJump_RH_25_11,

            Man_WalkingJump_RH_1D_25_01,
            Man_WalkingJump_RH_1D_25_02,
            Man_WalkingJump_RH_1D_25_03,
            Man_WalkingJump_RH_1D_25_04,
            Man_WalkingJump_RH_1D_25_05,
            Man_WalkingJump_RH_1D_25_06,
            Man_WalkingJump_RH_1D_25_07,
            Man_WalkingJump_RH_1D_25_08,
            Man_WalkingJump_RH_1D_25_09,
            Man_WalkingJump_RH_1D_25_10,
            Man_WalkingJump_RH_1D_25_11,
            
            Man_WalkingJump_RH_UP_01,
            Man_WalkingJump_RH_UP_02,
            Man_WalkingJump_RH_UP_03,
            Man_WalkingJump_RH_UP_04,
            Man_WalkingJump_RH_UP_05,
            
            Man_Rope_Start_RH,

                Man_Rope_Start_RH_01 = Man_Rope_Start_RH,
                Man_Rope_Start_RH_02,
                Man_Rope_Start_RH_03,
                Man_Rope_Start_RH_04,
                Man_Rope_Start_RH_05,
                Man_Rope_Start_RH_06,
                Man_Rope_Start_RH_07,
                
                Man_Rope_End_RH_01,
                Man_Rope_End_RH_02,
                Man_Rope_End_RH_03,
                Man_Rope_End_RH_04,
                Man_Rope_End_RH_05,
                Man_Rope_End_RH_06,

            Man_Rope_End_RH = Man_Rope_End_RH_06,

            Man_BounceJump_RH_01,
            Man_BounceJump_RH_02,
            Man_BounceJump_RH_03,
            Man_BounceJump_RH_04,
            Man_BounceJump_RH_05,
            Man_BounceJump_RH_06,
            Man_BounceJump_RH_07,
            Man_BounceJump_RH_08,
            Man_BounceJump_RH_09,
            Man_BounceJump_RH_10,
            Man_BounceJump_RH_11,
            Man_BounceJump_RH_12,
            Man_BounceJump_RH_13,
            Man_BounceJump_RH_14,
            Man_BounceJump_RH_15,
            Man_BounceJump_RH_16,
            Man_BounceJump_RH_17,
            Man_BounceJump_RH_18,
            Man_BounceJump_RH_19,
            Man_BounceJump_RH_20,
            Man_BounceJump_RH_21,
            Man_BounceJump_RH_22,
            Man_BounceJump_RH_23,
            Man_BounceJump_RH_24,
            Man_BounceJump_RH_25,
            Man_BounceJump_RH_26,
            Man_BounceJump_RH_27,
            Man_BounceJump_RH_28,
            Man_BounceJump_RH_29,
            Man_BounceJump_RH_30,
            Man_BounceJump_RH_31,
            Man_BounceJump_RH_32,
            Man_BounceJump_RH_33,
            Man_BounceJump_RH_34,

            Man_Slide_RH_01,
            Man_Slide_RH_02,
            Man_Slide_RH_03,
            Man_Slide_RH_04,
            Man_Slide_RH_05,
            Man_Slide_RH_06,
            Man_Slide_RH_07,
            Man_Slide_RH_08,
            Man_Slide_RH_09,
            Man_Slide_RH_10,
            Man_Slide_RH_11,

            Man_Slide_RH_Full_01,
            Man_Slide_RH_Full_02,
            Man_Slide_RH_Full_03,
            Man_Slide_RH_Full_04,
            Man_Slide_RH_Full_05,
            Man_Slide_RH_Full_06,
            Man_Slide_RH_Full_07,
            Man_Slide_RH_Full_08,
            Man_Slide_RH_Full_09,
            Man_Slide_RH_Full_10,
            Man_Slide_RH_Full_11,
            Man_Slide_RH_Full_12,
            Man_Slide_RH_Full_13,

            Man_Slide_RH_Full_Land_01,
            Man_Slide_RH_Full_Land_02,
            Man_Slide_RH_Full_Land_03,
            Man_Slide_RH_Full_Land_04,
            Man_Slide_RH_Full_Land_05,
            Man_Slide_RH_Full_Land_06,
            Man_Slide_RH_Full_Land_07,
            Man_Slide_RH_Full_Land_08,
            Man_Slide_RH_Full_Land_09,
            Man_Slide_RH_Full_Land_10,
            Man_Slide_RH_Full_Land_11,
            Man_Slide_RH_Full_Land_12,
            Man_Slide_RH_Full_Land_13,
            
            Man_Die_RH_01,
            Man_Die_RH_02,
            Man_Die_RH_03,
            Man_Die_RH_04,

        Man_RH_End = Man_Die_RH_04,
        
        Man_FW_Start,
            
            Man_Walk_FW_01 = Man_FW_Start,
            Man_Walk_FW_02,
            Man_Walk_FW_03,
            Man_Walk_FW_04,

            Man_StandingJump_FW_01,
            Man_StandingJump_FW_02,
            Man_StandingJump_FW_03,
            Man_StandingJump_FW_04,
            Man_StandingJump_FW_05,
            Man_StandingJump_FW_06,
            Man_StandingJump_FW_07,

            Man_StandingJump_FW_UP_01,     // Jump Up
            Man_StandingJump_FW_UP_02,
            Man_StandingJump_FW_UP_03,
            Man_StandingJump_FW_UP_04,
            Man_StandingJump_FW_UP_05,
            Man_StandingJump_FW_UP_06,

        Man_FW_End = Man_StandingJump_FW_UP_06,
        
        Man_LH_Start,
                
            Man_Walk_LH_00 = Man_LH_Start,                 // No movement
            Man_Walk_LH_01,
            Man_Walk_LH_02,
            Man_Walk_LH_03,
            Man_Walk_LH_04,

            Man_ClimbStairs_LH_01,
            Man_ClimbStairs_LH_02,
            Man_ClimbStairs_LH_03,
            Man_ClimbStairs_LH_04,
            Man_ClimbStairs_LH_05,
            Man_ClimbStairs_LH_06,
            Man_ClimbStairs_LH_07,
            Man_ClimbStairs_LH_08,

            Man_ClimbStairs_LH_Half_01,
            Man_ClimbStairs_LH_Half_02,
            Man_ClimbStairs_LH_Half_03,
            Man_ClimbStairs_LH_Half_04,

            Man_DescendStairs_LH_01,
            Man_DescendStairs_LH_02,
            Man_DescendStairs_LH_03,
            Man_DescendStairs_LH_04,
            Man_DescendStairs_LH_05,
            Man_DescendStairs_LH_06,
            Man_DescendStairs_LH_07,
            Man_DescendStairs_LH_08,

            Man_DescendStairs_LH_Half_01,
            Man_DescendStairs_LH_Half_02,
            Man_DescendStairs_LH_Half_03,
            Man_DescendStairs_LH_Half_04,

            Man_Walk_FallDown_LH_01,
            Man_Walk_FallDown_LH_02,
            Man_Walk_FallDown_LH_03,
            Man_Walk_FallDown_LH_04,
            Man_Walk_FallDown_LH_05,
            Man_Walk_FallDown_LH_06,

            Man_Walk_FallMore_LH_01,
            Man_Walk_FallMore_LH_02,

            Man_Walk_FallLand_LH_01,
            Man_Walk_FallLand_LH_02,
            Man_Walk_FallLand_LH_03,
            Man_Walk_FallLand_LH_04,

            Man_StandingJump_LH_01,
            Man_StandingJump_LH_02,
            Man_StandingJump_LH_03,
            Man_StandingJump_LH_04,
            Man_StandingJump_LH_05,
            Man_StandingJump_LH_06,
            Man_StandingJump_LH_07,

            Man_StandingJump_Small_LH_01,
            Man_StandingJump_Small_LH_02,
            Man_StandingJump_Small_LH_03,
                    
            Man_StandingJump_LH_UP_01,     // Jump Up
            Man_StandingJump_LH_UP_02,
            Man_StandingJump_LH_UP_03,
            Man_StandingJump_LH_UP_04,
            Man_StandingJump_LH_UP_05,
            Man_StandingJump_LH_UP_06,
                    
            Man_StandingJump_LH_UPandOver_01,     // Jump Up
            Man_StandingJump_LH_UPandOver_02,
            Man_StandingJump_LH_UPandOver_03,
            Man_StandingJump_LH_UPandOver_04,
            Man_StandingJump_LH_UPandOver_05,
            Man_StandingJump_LH_UPandOver_06,

            Man_WalkingJump_LH_01,
            Man_WalkingJump_LH_02,
            Man_WalkingJump_LH_03,
            Man_WalkingJump_LH_04,
            Man_WalkingJump_LH_05,
            Man_WalkingJump_LH_06,
            Man_WalkingJump_LH_07,
            Man_WalkingJump_LH_08,

            Man_WalkingJump_LH_2_01,
            Man_WalkingJump_LH_2_02,
            Man_WalkingJump_LH_2_03,
            Man_WalkingJump_LH_2_04,
            Man_WalkingJump_LH_2_05,
            Man_WalkingJump_LH_2_06,
            Man_WalkingJump_LH_2_07,
            Man_WalkingJump_LH_2_08,
            
            Man_WalkingJump_LH_25_01,
            Man_WalkingJump_LH_25_02,
            Man_WalkingJump_LH_25_03,
            Man_WalkingJump_LH_25_04,
            Man_WalkingJump_LH_25_05,
            Man_WalkingJump_LH_25_06,
            Man_WalkingJump_LH_25_07,
            Man_WalkingJump_LH_25_08,
            Man_WalkingJump_LH_25_09,
            Man_WalkingJump_LH_25_10,
            Man_WalkingJump_LH_25_11,
            
            Man_WalkingJump_LH_1D_25_01,
            Man_WalkingJump_LH_1D_25_02,
            Man_WalkingJump_LH_1D_25_03,
            Man_WalkingJump_LH_1D_25_04,
            Man_WalkingJump_LH_1D_25_05,
            Man_WalkingJump_LH_1D_25_06,
            Man_WalkingJump_LH_1D_25_07,
            Man_WalkingJump_LH_1D_25_08,
            Man_WalkingJump_LH_1D_25_09,
            Man_WalkingJump_LH_1D_25_10,
            Man_WalkingJump_LH_1D_25_11,
            
            Man_WalkingJump_LH_UP_01,
            Man_WalkingJump_LH_UP_02,
            Man_WalkingJump_LH_UP_03,
            Man_WalkingJump_LH_UP_04,
            Man_WalkingJump_LH_UP_05,

            Man_Rope_Start_LH,

                Man_Rope_Start_LH_01 = Man_Rope_Start_LH,
                Man_Rope_Start_LH_02,
                Man_Rope_Start_LH_03,
                Man_Rope_Start_LH_04,
                Man_Rope_Start_LH_05,
                Man_Rope_Start_LH_06,
                Man_Rope_Start_LH_07,
                
                Man_Rope_End_LH_01,
                Man_Rope_End_LH_02,
                Man_Rope_End_LH_03,
                Man_Rope_End_LH_04,
                Man_Rope_End_LH_05,
                Man_Rope_End_LH_06,

            Man_Rope_End_LH = Man_Rope_End_LH_06,

            Man_BounceJump_LH_01,
            Man_BounceJump_LH_02,
            Man_BounceJump_LH_03,
            Man_BounceJump_LH_04,
            Man_BounceJump_LH_05,
            Man_BounceJump_LH_06,
            Man_BounceJump_LH_07,
            Man_BounceJump_LH_08,
            Man_BounceJump_LH_09,
            Man_BounceJump_LH_10,
            Man_BounceJump_LH_11,
            Man_BounceJump_LH_12,
            Man_BounceJump_LH_13,
            Man_BounceJump_LH_14,
            Man_BounceJump_LH_15,
            Man_BounceJump_LH_16,
            Man_BounceJump_LH_17,
            Man_BounceJump_LH_18,
            Man_BounceJump_LH_19,
            Man_BounceJump_LH_20,
            Man_BounceJump_LH_21,
            Man_BounceJump_LH_22,
            Man_BounceJump_LH_23,
            Man_BounceJump_LH_24,
            Man_BounceJump_LH_25,
            Man_BounceJump_LH_26,
            Man_BounceJump_LH_27,
            Man_BounceJump_LH_28,
            Man_BounceJump_LH_29,
            Man_BounceJump_LH_30,
            Man_BounceJump_LH_31,
            Man_BounceJump_LH_32,
            Man_BounceJump_LH_33,
            Man_BounceJump_LH_34,

            Man_Slide_LH_01,
            Man_Slide_LH_02,
            Man_Slide_LH_03,
            Man_Slide_LH_04,
            Man_Slide_LH_05,
            Man_Slide_LH_06,
            Man_Slide_LH_07,
            Man_Slide_LH_08,
            Man_Slide_LH_09,
            Man_Slide_LH_10,
            Man_Slide_LH_11,

            Man_Slide_LH_Full_01,
            Man_Slide_LH_Full_02,
            Man_Slide_LH_Full_03,
            Man_Slide_LH_Full_04,
            Man_Slide_LH_Full_05,
            Man_Slide_LH_Full_06,
            Man_Slide_LH_Full_07,
            Man_Slide_LH_Full_08,
            Man_Slide_LH_Full_09,
            Man_Slide_LH_Full_10,
            Man_Slide_LH_Full_11,
            Man_Slide_LH_Full_12,
            Man_Slide_LH_Full_13,

            Man_Slide_LH_Full_Land_01,
            Man_Slide_LH_Full_Land_02,
            Man_Slide_LH_Full_Land_03,
            Man_Slide_LH_Full_Land_04,
            Man_Slide_LH_Full_Land_05,
            Man_Slide_LH_Full_Land_06,
            Man_Slide_LH_Full_Land_07,
            Man_Slide_LH_Full_Land_08,
            Man_Slide_LH_Full_Land_09,
            Man_Slide_LH_Full_Land_10,
            Man_Slide_LH_Full_Land_11,
            Man_Slide_LH_Full_Land_12,
            Man_Slide_LH_Full_Land_13,

            Man_Die_LH_01,
            Man_Die_LH_02,
            Man_Die_LH_03,
            Man_Die_LH_04,

        Man_LH_End = Man_Die_LH_04,
    
        Man_StandingJumpDown_RH_01,
        Man_StandingJumpDown_RH_02,
        Man_StandingJumpDown_RH_03,
        Man_StandingJumpDown_RH_04,
        Man_StandingJumpDown_RH_05,
        Man_StandingJumpDown_RH_06,
        Man_StandingJumpDown_RH_07,
        Man_StandingJumpDown_RH_08,
        Man_StandingJumpDown_RH_09,

    Man_End = Man_StandingJumpDown_RH_09,
    None = 255,
};

inline Stance &operator++(Stance &c) {
  c = static_cast<Stance>( static_cast<uint8_t>(c) + 1 );
  return c;
}

inline Stance operator++(Stance &c, int) {
  Stance result = c;
  ++c;
  return result;
}


enum class GameState : uint8_t {

    SplashScreen_Start,
        SplashScreen_00 = SplashScreen_Start,
        SplashScreen_01,
        SplashScreen_02,
        SplashScreen_03,
    SplashScreen_End,

    Title_Init,
    Title_Start,
        Title_OptPlay = Title_Start,
        Title_OptSound,
        Title_OptCredits,
        Title_OptResume,
        Title_OptPlay2,
        Title_OptSound2,
        Title_OptSound_Music,
        Title_OptSound_SFX,
        Title_OptSound_Volume,
        Title_OptSound_Music2,
        Title_OptSound_SFX2,
        Title_OptSound_Volume2,
        Title_ShowCredits,
    Title_End,

    Play_Init,
    Play_Start,
        Play_BoatEnters,
        Play_PlayerJumps,
        Play_PlayerCenters,
        Play,
    Play_End,
    PlayGame_Init,
    PlayGame_Start,
        PlayGame,
    PlayGame_End,
    Map_Init,
    Map,
    Map_ShowDialogue,
    Map_MoveBoat,
};

inline GameState &operator++(GameState &c) {
  c = static_cast<GameState>( static_cast<uint8_t>(c) + 1 );
  return c;
}

inline GameState operator++(GameState &c, int) {
  GameState result = c;
  ++c;
  return result;
}
