#pragma once

#include <Arduboy2.h>

struct BoatMovement {

    int8_t x;
    int8_t y;        
    uint8_t direction;
};


struct StanceDetails {

    int8_t stanceY;
    int8_t foreground;        
    int8_t middleground;        
    int8_t background;        
    
};


enum class MusicSong : uint8_t {
    MainTheme
};

enum class MusicSFX : uint8_t {
    SFX_Death,
    SFX_Victory,
    SFX_XPGain,
    SFX_Three_Inc,
    SFX_Three_Dec,
    SFX_PlayerBlip,
    SFX_EnemyBlip,
    SFX_Explosion,
    SFX_DoubleBeep,
    SFX_DoubleBeepDown,
    SFX_Bet1,
    SFX_Bet2,
    SFX_Bet3,
    SFX_Bet4,
    SFX_Bet5,
    SFX_Bet6,
    SFX_Click,
    SFX_SmallBlind,
    SFX_BigBlind,
};

enum class BoatDirection : uint8_t {
    Up,
    UpRight,
    Right,
    DownRight,
    Down,
    DownLeft,
    Left,
    UpLeft,
    None = 255,
};

enum class Direction : uint8_t {
    Backward,
    Right,
    Forward,
    Left,
    None,
};

enum class EnemyType : uint8_t {
    None,
    Archer,
    TrebochetOperator,
    SwordFighter,
};

enum class ItemType : uint8_t {
    Key1,
    Key1_Hidden,
    WoodenBarrier,
    TrapDoor,
    Punji,
    Hammer,
    Hammer_Hidden,
    Amulet,
    Amulet_Hidden,
    PinchBar,
    PinchBar_Hidden,
    MysteryCrate,
    Potion,
    Potion_Hidden,
    LockedDoor,
    LockedDoor_Hidden,
    Anchor,
    Anchor_Hidden,
    Swinging_Vine,
    Swinging_Vine_Hidden,
    Flame,
    Flane_Hidden,
    Arrow_LH,
    Arrow_LH_Hidden,
    Arrow_RH,
    Arrow_RH_Hidden,
    Sword,
    Sword_Hidden,
    Trebochet_Left,
    Trebochet_Right,
    Trebochet_Ball_Left_1, // 6
    Trebochet_Ball_Left_2, // 5, 6
    Trebochet_Ball_Left_3, // 5
    Trebochet_Ball_Left_Hidden,
    Trebochet_Ball_Right_1, // 6
    Trebochet_Ball_Right_2, // 5, 6
    Trebochet_Ball_Right_3, // 5
    Trebochet_Ball_Right_Hidden,
    SwingyThing,
    SwingyThing_2,
    SwingyThing_Hidden,
    Chakana,
    Chakana_Hidden,
    Lever_LH,
    Lever_RH,
    Lever_Portal_Closed,
    Lever_Portal_Open,
    Lever_Portal_Auto_Closed,
    Lever_Portal_Auto_Open,
    Glint,
    Glint_Hidden,
    LifeSaver,
    LifeSaver_Hidden,
    LifeSaver_InWater_LH,
    LifeSaver_InWater_RH,
    LifeSaver_Dissolve,
    LifeSaver_Dissolve_Hidden,
    LifeSaver_Dissolve_InWater_LH,
    LifeSaver_Dissolve_InWater_RH,
    Chakana_Small,
    Chakana_Small_Hidden,
    Poker,
    Poker_Hidden,
    Puff,
    None,
};


inline ItemType &operator++(ItemType &c) {
  c = static_cast<ItemType>( static_cast<uint8_t>(c) + 1 );
  return c;
};

inline ItemType operator++(ItemType &c, int) {
  ItemType result = c;
  ++c;
  return result;
};

inline ItemType &operator--( ItemType & c ) {
  c = static_cast<ItemType>( static_cast<uint8_t>(c) - 1 );
  return c;
};

inline ItemType operator--( ItemType & c, int ) {
  ItemType result = c;
  --c;
  return result;
};


enum class ItemAction : uint8_t {
    None,
    Remove,
    Remove_AddToInventory,
    HideCrate_ShowItem,
    ChangeToHidden,
};


enum Stance : uint16_t {

    Man_Start,

        Man_BK_Start = Man_Start,

            Man_Walk_BK_01 = Man_BK_Start,
            Man_Walk_BK_02,
            Man_Walk_BK_03,
            Man_Walk_BK_04,
            
            Man_StandingJump_BK_01,
            Man_StandingJump_BK_02,
            Man_StandingJump_BK_03,
            Man_StandingJump_BK_04,
            Man_StandingJump_BK_05,
            Man_StandingJump_BK_06,
            Man_StandingJump_BK_07,

            Man_StandingJump_BK_UP_01,     // Jump Up
            Man_StandingJump_BK_UP_02,
            Man_StandingJump_BK_UP_03,
            Man_StandingJump_BK_UP_04,
            Man_StandingJump_BK_UP_05,
            Man_StandingJump_BK_UP_06,

            Man_ClimbLadder_BK_RH_UP_01,
            Man_ClimbLadder_BK_RH_UP_02,
            Man_ClimbLadder_BK_RH_UP_03,
            Man_ClimbLadder_BK_RH_UP_04,
            Man_ClimbLadder_BK_RH_UP_05,
            Man_ClimbLadder_BK_RH_UP_06,
            Man_ClimbLadder_BK_RH_UP_07,
            Man_ClimbLadder_BK_RH_UP_08,
            Man_ClimbLadder_BK_RH_UP_09,
            Man_ClimbLadder_BK_RH_UP_10,
            Man_ClimbLadder_BK_RH_UP_11,
            Man_ClimbLadder_BK_RH_UP_12,
            Man_ClimbLadder_BK_RH_UP_13,
            Man_ClimbLadder_BK_RH_UP_14,

            Man_ClimbLadder_More_BK_RH_UP_01,
            Man_ClimbLadder_More_BK_RH_UP_02,
            Man_ClimbLadder_More_BK_RH_UP_03,
            Man_ClimbLadder_More_BK_RH_UP_04,

            Man_ClimbLadder_BK_RH_DOWN_01,
            Man_ClimbLadder_BK_RH_DOWN_02,
            Man_ClimbLadder_BK_RH_DOWN_03,
            Man_ClimbLadder_BK_RH_DOWN_04,
            Man_ClimbLadder_BK_RH_DOWN_05,
            Man_ClimbLadder_BK_RH_DOWN_06,
            Man_ClimbLadder_BK_RH_DOWN_07,
            Man_ClimbLadder_BK_RH_DOWN_08,
            Man_ClimbLadder_BK_RH_DOWN_09,
            Man_ClimbLadder_BK_RH_DOWN_10,
            Man_ClimbLadder_BK_RH_DOWN_11,
            Man_ClimbLadder_BK_RH_DOWN_12,
            Man_ClimbLadder_BK_RH_DOWN_13,
            Man_ClimbLadder_BK_RH_DOWN_14,

            Man_ClimbLadder_More_BK_RH_DOWN_01,
            Man_ClimbLadder_More_BK_RH_DOWN_02,
            Man_ClimbLadder_More_BK_RH_DOWN_03,
            Man_ClimbLadder_More_BK_RH_DOWN_04,

            Man_ClimbLadder_BK_LH_UP_01,
            Man_ClimbLadder_BK_LH_UP_02,
            Man_ClimbLadder_BK_LH_UP_03,
            Man_ClimbLadder_BK_LH_UP_04,
            Man_ClimbLadder_BK_LH_UP_05,
            Man_ClimbLadder_BK_LH_UP_06,
            Man_ClimbLadder_BK_LH_UP_07,
            Man_ClimbLadder_BK_LH_UP_08,
            Man_ClimbLadder_BK_LH_UP_09,
            Man_ClimbLadder_BK_LH_UP_10,
            Man_ClimbLadder_BK_LH_UP_11,
            Man_ClimbLadder_BK_LH_UP_12,
            Man_ClimbLadder_BK_LH_UP_13,
            Man_ClimbLadder_BK_LH_UP_14,

            Man_ClimbLadder_More_BK_LH_UP_01,
            Man_ClimbLadder_More_BK_LH_UP_02,
            Man_ClimbLadder_More_BK_LH_UP_03,
            Man_ClimbLadder_More_BK_LH_UP_04,

            Man_ClimbLadder_BK_LH_DOWN_01,
            Man_ClimbLadder_BK_LH_DOWN_02,
            Man_ClimbLadder_BK_LH_DOWN_03,
            Man_ClimbLadder_BK_LH_DOWN_04,
            Man_ClimbLadder_BK_LH_DOWN_05,
            Man_ClimbLadder_BK_LH_DOWN_06,
            Man_ClimbLadder_BK_LH_DOWN_07,
            Man_ClimbLadder_BK_LH_DOWN_08,
            Man_ClimbLadder_BK_LH_DOWN_09,
            Man_ClimbLadder_BK_LH_DOWN_10,
            Man_ClimbLadder_BK_LH_DOWN_11,
            Man_ClimbLadder_BK_LH_DOWN_12,
            Man_ClimbLadder_BK_LH_DOWN_13,
            Man_ClimbLadder_BK_LH_DOWN_14,

            Man_ClimbLadder_More_BK_LH_DOWN_01,
            Man_ClimbLadder_More_BK_LH_DOWN_02,
            Man_ClimbLadder_More_BK_LH_DOWN_03,
            Man_ClimbLadder_More_BK_LH_DOWN_04,

            Man_Walk_FallMore_BK_01,
            Man_Walk_FallMore_BK_02,

            Man_Walk_FallLand_BK_01,
            Man_Walk_FallLand_BK_02,
            Man_Walk_FallLand_BK_03,
            Man_Walk_FallLand_BK_04,

            Man_Walk_FallLandSpring_BK_01,
            Man_Walk_FallLandSpring_BK_02,
            Man_Walk_FallLandSpring_BK_03,
            Man_Walk_FallLandSpring_BK_04,
            Man_Walk_FallLandSpring_BK_05,
            Man_Walk_FallLandSpring_BK_06,
            Man_Walk_FallLandSpring_BK_07,
            Man_Walk_FallLandSpring_BK_08,
            Man_Walk_FallLandSpring_BK_09,
            Man_Walk_FallLandSpring_BK_10,
            Man_Walk_FallLandSpring_BK_11,
            Man_Walk_FallLandSpring_BK_12,
            Man_Walk_FallLandSpring_BK_13,
            Man_Walk_FallLandSpring_BK_14,
            Man_Walk_FallLandSpring_BK_15,
            Man_Walk_FallLandSpring_BK_16,
            Man_Walk_FallLandSpring_BK_17,
            Man_Walk_FallLandSpring_BK_18,
            Man_Walk_FallLandSpring_BK_19,
            Man_Walk_FallLandSpring_BK_20,
            Man_Walk_FallLandSpring_BK_21,
            Man_Walk_FallLandSpring_BK_22,
            Man_Walk_FallLandSpring_BK_23,
            Man_Walk_FallLandSpring_BK_24,
            Man_Walk_FallLandSpring_BK_25,
            Man_Walk_FallLandSpring_BK_26,
            Man_Walk_FallLandSpring_BK_27,
            Man_Walk_FallLandSpring_BK_28,

        Man_BK_End = Man_Walk_FallLandSpring_BK_28,
        
        Man_RH_Start,

            Man_Walk_RH_00 = Man_RH_Start,                 // No movement
            Man_Walk_RH_01,
            Man_Walk_RH_02,
            Man_Walk_RH_03,
            Man_Walk_RH_04,
            Man_Walk_RH_05,
            Man_Walk_RH_06,
            Man_Walk_RH_07,
            Man_Walk_RH_08,

            Man_ClimbStairs_RH_01,
            Man_ClimbStairs_RH_02,
            Man_ClimbStairs_RH_03,
            Man_ClimbStairs_RH_04,
            Man_ClimbStairs_RH_05,
            Man_ClimbStairs_RH_06,
            Man_ClimbStairs_RH_07,
            Man_ClimbStairs_RH_08,

            Man_ClimbStairs_RH_Half_01,
            Man_ClimbStairs_RH_Half_02,
            Man_ClimbStairs_RH_Half_03,
            Man_ClimbStairs_RH_Half_04,

            Man_DescendStairs_RH_01,
            Man_DescendStairs_RH_02,
            Man_DescendStairs_RH_03,
            Man_DescendStairs_RH_04,
            Man_DescendStairs_RH_05,
            Man_DescendStairs_RH_06,
            Man_DescendStairs_RH_07,
            Man_DescendStairs_RH_08,

            Man_DescendStairs_RH_Half_01,
            Man_DescendStairs_RH_Half_02,
            Man_DescendStairs_RH_Half_03,
            Man_DescendStairs_RH_Half_04,

            Man_Walk_FallDown_RH_01,
            Man_Walk_FallDown_RH_02,
            Man_Walk_FallDown_RH_03,
            Man_Walk_FallDown_RH_04,
            Man_Walk_FallDown_RH_05,
            Man_Walk_FallDown_RH_06,

            Man_Walk_FallMore_RH_01,
            Man_Walk_FallMore_RH_02,

            Man_Walk_FallLand_RH_01,
            Man_Walk_FallLand_RH_02,
            Man_Walk_FallLand_RH_03,
            Man_Walk_FallLand_RH_04,

            Man_Walk_FallLand_RH_01_Puff,
            Man_Walk_FallLand_RH_02_Puff,
            Man_Walk_FallLand_RH_03_Puff,
            Man_Walk_FallLand_RH_04_Puff,

            Man_StandingJump_RH_01,
            Man_StandingJump_RH_02,
            Man_StandingJump_RH_03,
            Man_StandingJump_RH_04,
            Man_StandingJump_RH_05,
            Man_StandingJump_RH_06,
            Man_StandingJump_RH_07,
            
            Man_StandingJump_Small_RH_01,
            Man_StandingJump_Small_RH_02,
            Man_StandingJump_Small_RH_03,

            Man_StandingJump_RH_UP_01,     // Jump Up
            Man_StandingJump_RH_UP_02,
            Man_StandingJump_RH_UP_03,
            Man_StandingJump_RH_UP_04,
            Man_StandingJump_RH_UP_05,
            Man_StandingJump_RH_UP_06,
                    
            Man_StandingJump_RH_UPandOver_01,     // Jump Up
            Man_StandingJump_RH_UPandOver_02,
            Man_StandingJump_RH_UPandOver_03,
            Man_StandingJump_RH_UPandOver_04,
            Man_StandingJump_RH_UPandOver_05,
            Man_StandingJump_RH_UPandOver_06,
            
            Man_WalkingJump_RH_01,
            Man_WalkingJump_RH_02,
            Man_WalkingJump_RH_03,
            Man_WalkingJump_RH_04,
            Man_WalkingJump_RH_05,
            Man_WalkingJump_RH_06,
            Man_WalkingJump_RH_07,
            Man_WalkingJump_RH_08,

            Man_WalkingJump_RH_2_01,
            Man_WalkingJump_RH_2_02,
            Man_WalkingJump_RH_2_03,
            Man_WalkingJump_RH_2_04,
            Man_WalkingJump_RH_2_05,
            Man_WalkingJump_RH_2_06,
            Man_WalkingJump_RH_2_07,
            Man_WalkingJump_RH_2_08,

            Man_WalkingJump_RH_25_01,
            Man_WalkingJump_RH_25_02,
            Man_WalkingJump_RH_25_03,
            Man_WalkingJump_RH_25_04,
            Man_WalkingJump_RH_25_05,
            Man_WalkingJump_RH_25_06,
            Man_WalkingJump_RH_25_07,
            Man_WalkingJump_RH_25_08,
            Man_WalkingJump_RH_25_09,
            Man_WalkingJump_RH_25_10,
            Man_WalkingJump_RH_25_11,

            Man_WalkingJump_RH_1D_25_01,
            Man_WalkingJump_RH_1D_25_02,
            Man_WalkingJump_RH_1D_25_03,
            Man_WalkingJump_RH_1D_25_04,
            Man_WalkingJump_RH_1D_25_05,
            Man_WalkingJump_RH_1D_25_06,
            Man_WalkingJump_RH_1D_25_07,
            Man_WalkingJump_RH_1D_25_08,
            Man_WalkingJump_RH_1D_25_09,
            Man_WalkingJump_RH_1D_25_10,
            Man_WalkingJump_RH_1D_25_11,

            Man_WalkingJump_RH_2D_25_01,
            Man_WalkingJump_RH_2D_25_02,
            Man_WalkingJump_RH_2D_25_03,
            Man_WalkingJump_RH_2D_25_04,
            Man_WalkingJump_RH_2D_25_05,
            Man_WalkingJump_RH_2D_25_06,
            Man_WalkingJump_RH_2D_25_07,
            Man_WalkingJump_RH_2D_25_08,
            Man_WalkingJump_RH_2D_25_09,
            Man_WalkingJump_RH_2D_25_10,
            Man_WalkingJump_RH_2D_25_11,
            
            Man_WalkingJump_RH_UP_01,
            Man_WalkingJump_RH_UP_02,
            Man_WalkingJump_RH_UP_03,
            Man_WalkingJump_RH_UP_04,
            Man_WalkingJump_RH_UP_05,
            
            Man_Rope_Start_RH,

                Man_Rope_Start_RH_01 = Man_Rope_Start_RH,
                Man_Rope_Start_RH_02,
                Man_Rope_Start_RH_03,
                Man_Rope_Start_RH_04,
                Man_Rope_Start_RH_05,
                Man_Rope_Start_RH_06,
                Man_Rope_Start_RH_07,
                
                Man_Rope_End_RH_01,
                Man_Rope_End_RH_02,
                Man_Rope_End_RH_03,
                Man_Rope_End_RH_04,
                Man_Rope_End_RH_05,
                Man_Rope_End_RH_06,

            Man_Rope_End_RH = Man_Rope_End_RH_06,

            Man_BounceJump_RH_01,
            Man_BounceJump_RH_02,
            Man_BounceJump_RH_03,
            Man_BounceJump_RH_04,
            Man_BounceJump_RH_05,
            Man_BounceJump_RH_06,
            Man_BounceJump_RH_07,
            Man_BounceJump_RH_08,
            Man_BounceJump_RH_09,
            Man_BounceJump_RH_10,
            Man_BounceJump_RH_11,
            Man_BounceJump_RH_12,
            Man_BounceJump_RH_13,
            Man_BounceJump_RH_14,
            Man_BounceJump_RH_15,
            Man_BounceJump_RH_16,
            Man_BounceJump_RH_17,
            Man_BounceJump_RH_18,
            Man_BounceJump_RH_19,
            Man_BounceJump_RH_20,
            Man_BounceJump_RH_21,
            Man_BounceJump_RH_22,
            Man_BounceJump_RH_23,
            Man_BounceJump_RH_24,
            Man_BounceJump_RH_25,
            Man_BounceJump_RH_26,
            Man_BounceJump_RH_27,
            Man_BounceJump_RH_28,
            Man_BounceJump_RH_29,
            Man_BounceJump_RH_30,
            Man_BounceJump_RH_31,
            Man_BounceJump_RH_32,
            Man_BounceJump_RH_33,
            Man_BounceJump_RH_34,

            Man_Slide_RH_01,
            Man_Slide_RH_02,
            Man_Slide_RH_03,
            Man_Slide_RH_04,
            Man_Slide_RH_05,
            Man_Slide_RH_06,
            Man_Slide_RH_07,
            Man_Slide_RH_08,
            Man_Slide_RH_09,
            Man_Slide_RH_10,
            Man_Slide_RH_11,

            Man_Slide_RH_Full_01,
            Man_Slide_RH_Full_02,
            Man_Slide_RH_Full_03,
            Man_Slide_RH_Full_04,
            Man_Slide_RH_Full_05,
            Man_Slide_RH_Full_06,
            Man_Slide_RH_Full_07,
            Man_Slide_RH_Full_08,
            Man_Slide_RH_Full_09,
            Man_Slide_RH_Full_10,
            Man_Slide_RH_Full_11,
            Man_Slide_RH_Full_12,
            Man_Slide_RH_Full_13,

            Man_Slide_RH_Full_CanCont_01,
            Man_Slide_RH_Full_CanCont_02,
            Man_Slide_RH_Full_CanCont_03,
            Man_Slide_RH_Full_CanCont_04,
            Man_Slide_RH_Full_CanCont_05,
            Man_Slide_RH_Full_CanCont_06,
            Man_Slide_RH_Full_CanCont_07,
            Man_Slide_RH_Full_CanCont_08,
            Man_Slide_RH_Full_CanCont_09,
            Man_Slide_RH_Full_CanCont_10,
            Man_Slide_RH_Full_CanCont_11,
            Man_Slide_RH_Full_CanCont_12,
            Man_Slide_RH_Full_CanCont_13,

            Man_Slide_RH_Full_Cont_01,
            Man_Slide_RH_Full_Cont_02,
            Man_Slide_RH_Full_Cont_03,
            Man_Slide_RH_Full_Cont_04,
            Man_Slide_RH_Full_Cont_05,
            Man_Slide_RH_Full_Cont_06,
            Man_Slide_RH_Full_Cont_07,
            Man_Slide_RH_Full_Cont_08,

            Man_Slide_RH_Full_Land_01,
            Man_Slide_RH_Full_Land_02,
            Man_Slide_RH_Full_Land_03,
            Man_Slide_RH_Full_Land_04,
            Man_Slide_RH_Full_Land_05,
            Man_Slide_RH_Full_Land_06,
            Man_Slide_RH_Full_Land_07,
            Man_Slide_RH_Full_Land_08,
            Man_Slide_RH_Full_Land_09,
            Man_Slide_RH_Full_Land_10,
            Man_Slide_RH_Full_Land_11,
            Man_Slide_RH_Full_Land_12,
            Man_Slide_RH_Full_Land_13,

            Man_Hammering_RH_00,
            Man_Hammering_RH_01,
            Man_Hammering_RH_02,
            Man_Hammering_RH_03,
            Man_Hammering_RH_04,
            Man_Hammering_RH_05,
            Man_Hammering_RH_06,
            Man_Hammering_RH_07,
            Man_Hammering_RH_08,
            Man_Hammering_RH_09,
            Man_Hammering_RH_10,

            Man_Levering_RH_00,
            Man_Levering_RH_01,
            Man_Levering_RH_02,
            Man_Levering_RH_03,
            Man_Levering_RH_04,
            Man_Levering_RH_05,
            Man_Levering_RH_06,
            Man_Levering_RH_07,
            Man_Levering_RH_08,
            Man_Levering_RH_09,
            Man_Levering_RH_10,

            Man_Rollers_RH_01,
            Man_Rollers_RH_02,
            Man_Rollers_RH_03,
            Man_Rollers_RH_04,

            Man_Rollers_Stand_RH_01,
            Man_Rollers_Stand_RH_02,
            Man_Rollers_Stand_RH_03,
            Man_Rollers_Stand_RH_04,

            Man_Rollers_Fall_RH_01,
            Man_Rollers_Fall_RH_02,
            Man_Rollers_Fall_RH_03,
            Man_Rollers_Fall_RH_04,
            Man_Rollers_Fall_RH_05,

            Man_Vine_RH_01,
            Man_Vine_RH_02,
            Man_Vine_RH_03,
            Man_Vine_RH_04,
            Man_Vine_RH_05,
            Man_Vine_RH_06,
            Man_Vine_RH_07,
            Man_Vine_RH_08,
            Man_Vine_RH_09,
            Man_Vine_RH_10,
            Man_Vine_RH_11,
            Man_Vine_RH_12,
            Man_Vine_RH_13,
            Man_Vine_RH_14,
            Man_Vine_RH_15,
            Man_Vine_RH_16,
            Man_Vine_RH_17,
            Man_Vine_RH_18,
            Man_Vine_RH_19,
            Man_Vine_RH_20,

            Man_Vine_Start_RH,

                Man_Vine_Exit_RH_01 = Man_Vine_Start_RH,
                Man_Vine_Exit_RH_02,
                Man_Vine_Exit_RH_03,
                Man_Vine_Exit_RH_04,
                Man_Vine_Exit_RH_05,
                Man_Vine_Exit_RH_06,
                Man_Vine_Exit_RH_07,
                Man_Vine_Exit_RH_08,
                
                Man_Vine_Entry_RH_01,
                Man_Vine_Entry_RH_02,
                Man_Vine_Entry_RH_03,
                Man_Vine_Entry_RH_04,
                Man_Vine_Entry_RH_05,
                Man_Vine_Entry_RH_06,
                Man_Vine_Entry_RH_07,
                Man_Vine_Entry_RH_08,

            Man_Vine_End_RH = Man_Vine_Entry_RH_08,

            Man_Sword_Start_RH,

                Man_Sword_Stationary_RH = Man_Sword_Start_RH,

                Man_Sword_Lunge_RH_01,
                Man_Sword_Lunge_RH_02,
                Man_Sword_Lunge_RH_03,
                Man_Sword_Lunge_RH_04,
                Man_Sword_Lunge_RH_05,
                Man_Sword_Lunge_RH_06,

                Man_Sword_Walk_RH_01,
                Man_Sword_Walk_RH_02,
                Man_Sword_Walk_RH_03,
                Man_Sword_Walk_RH_04,

                Man_Sword_Walk_BK_RH_01,
                Man_Sword_Walk_BK_RH_02,
                Man_Sword_Walk_BK_RH_03,
                Man_Sword_Walk_BK_RH_04,

                Man_Sword_StandingJump_RH_01,
                Man_Sword_StandingJump_RH_02,
                Man_Sword_StandingJump_RH_03,
                Man_Sword_StandingJump_RH_04,
                Man_Sword_StandingJump_RH_05,
                Man_Sword_StandingJump_RH_06,
                Man_Sword_StandingJump_RH_07,

            Man_Sword_End_RH = Man_Sword_StandingJump_RH_07,

            Man_Die_Fire_RH_01,
            Man_Die_Fire_RH_02,
            Man_Die_Fire_RH_03,
            Man_Die_Fire_RH_04,
            Man_Die_Fire_RH_05,
            Man_Die_Fire_RH_06,
            Man_Die_Fire_RH_07,
            Man_Die_Fire_RH_08,
            Man_Die_Fire_RH_09,
            Man_Die_Fire_RH_10,
            Man_Die_Fire_RH_11,
            Man_Die_Fire_RH_12,

            Man_Die_Fire_Adj_RH_01,
            Man_Die_Fire_Adj_RH_02,

            Man_Die_Arrow_FallForward_RH_01,
            Man_Die_Arrow_FallForward_RH_02,
            Man_Die_Arrow_FallForward_RH_03,
            Man_Die_Arrow_FallForward_RH_04,

            Man_Die_Arrow_FallBackward_RH_01,
            Man_Die_Arrow_FallBackward_RH_02,
            Man_Die_Arrow_FallBackward_RH_03,
            Man_Die_Arrow_FallBackward_RH_04,

            Man_Die_Fall_RH_01,
            Man_Die_Fall_RH_02,
            Man_Die_Fall_RH_03,
            Man_Die_Fall_RH_04,

            Man_Die_FWD_RH_01,
            Man_Die_FWD_RH_02,
            Man_Die_FWD_RH_03,
            Man_Die_FWD_RH_04,

            Man_Die_BWD_RH_01,
            Man_Die_BWD_RH_02,
            Man_Die_BWD_RH_03,
            Man_Die_BWD_RH_04,

            Man_Die_Water_RH_01,
            Man_Die_Water_RH_02,
            Man_Die_Water_RH_03,
            Man_Die_Water_RH_04,
            Man_Die_Water_RH_05,
            Man_Die_Water_RH_06,
            Man_Die_Water_RH_07,

            Man_Die_Water_RH_02_01,
            Man_Die_Water_RH_02_02,
            Man_Die_Water_RH_02_03,
            Man_Die_Water_RH_02_04,
            Man_Die_Water_RH_02_05,
            Man_Die_Water_RH_02_06,
            Man_Die_Water_RH_02_07,

        Man_RH_End = Man_Die_Water_RH_02_07,
        
        Man_FW_Start,
            
            Man_Walk_FW_01 = Man_FW_Start,
            Man_Walk_FW_02,
            Man_Walk_FW_03,
            Man_Walk_FW_04,

            Man_StandingJump_FW_01,
            Man_StandingJump_FW_02,
            Man_StandingJump_FW_03,
            Man_StandingJump_FW_04,
            Man_StandingJump_FW_05,
            Man_StandingJump_FW_06,
            Man_StandingJump_FW_07,

            Man_StandingJump_FW_UP_01,     // Jump Up
            Man_StandingJump_FW_UP_02,
            Man_StandingJump_FW_UP_03,
            Man_StandingJump_FW_UP_04,
            Man_StandingJump_FW_UP_05,
            Man_StandingJump_FW_UP_06,

        Man_FW_End = Man_StandingJump_FW_UP_06,
        
        Man_LH_Start,
                
            Man_Walk_LH_00 = Man_LH_Start,                 // No movement
            Man_Walk_LH_01,
            Man_Walk_LH_02,
            Man_Walk_LH_03,
            Man_Walk_LH_04,
            Man_Walk_LH_05,
            Man_Walk_LH_06,
            Man_Walk_LH_07,
            Man_Walk_LH_08,

            Man_ClimbStairs_LH_01,
            Man_ClimbStairs_LH_02,
            Man_ClimbStairs_LH_03,
            Man_ClimbStairs_LH_04,
            Man_ClimbStairs_LH_05,
            Man_ClimbStairs_LH_06,
            Man_ClimbStairs_LH_07,
            Man_ClimbStairs_LH_08,

            Man_ClimbStairs_LH_Half_01,
            Man_ClimbStairs_LH_Half_02,
            Man_ClimbStairs_LH_Half_03,
            Man_ClimbStairs_LH_Half_04,

            Man_DescendStairs_LH_01,
            Man_DescendStairs_LH_02,
            Man_DescendStairs_LH_03,
            Man_DescendStairs_LH_04,
            Man_DescendStairs_LH_05,
            Man_DescendStairs_LH_06,
            Man_DescendStairs_LH_07,
            Man_DescendStairs_LH_08,

            Man_DescendStairs_LH_Half_01,
            Man_DescendStairs_LH_Half_02,
            Man_DescendStairs_LH_Half_03,
            Man_DescendStairs_LH_Half_04,

            Man_Walk_FallDown_LH_01,
            Man_Walk_FallDown_LH_02,
            Man_Walk_FallDown_LH_03,
            Man_Walk_FallDown_LH_04,
            Man_Walk_FallDown_LH_05,
            Man_Walk_FallDown_LH_06,

            Man_Walk_FallMore_LH_01,
            Man_Walk_FallMore_LH_02,

            Man_Walk_FallLand_LH_01,
            Man_Walk_FallLand_LH_02,
            Man_Walk_FallLand_LH_03,
            Man_Walk_FallLand_LH_04,

            Man_Walk_FallLand_LH_01_Puff,
            Man_Walk_FallLand_LH_02_Puff,
            Man_Walk_FallLand_LH_03_Puff,
            Man_Walk_FallLand_LH_04_Puff,

            Man_StandingJump_LH_01,
            Man_StandingJump_LH_02,
            Man_StandingJump_LH_03,
            Man_StandingJump_LH_04,
            Man_StandingJump_LH_05,
            Man_StandingJump_LH_06,
            Man_StandingJump_LH_07,

            Man_StandingJump_Small_LH_01,
            Man_StandingJump_Small_LH_02,
            Man_StandingJump_Small_LH_03,
                    
            Man_StandingJump_LH_UP_01,     // Jump Up
            Man_StandingJump_LH_UP_02,
            Man_StandingJump_LH_UP_03,
            Man_StandingJump_LH_UP_04,
            Man_StandingJump_LH_UP_05,
            Man_StandingJump_LH_UP_06,
                    
            Man_StandingJump_LH_UPandOver_01,     // Jump Up
            Man_StandingJump_LH_UPandOver_02,
            Man_StandingJump_LH_UPandOver_03,
            Man_StandingJump_LH_UPandOver_04,
            Man_StandingJump_LH_UPandOver_05,
            Man_StandingJump_LH_UPandOver_06,

            Man_WalkingJump_LH_01,
            Man_WalkingJump_LH_02,
            Man_WalkingJump_LH_03,
            Man_WalkingJump_LH_04,
            Man_WalkingJump_LH_05,
            Man_WalkingJump_LH_06,
            Man_WalkingJump_LH_07,
            Man_WalkingJump_LH_08,

            Man_WalkingJump_LH_2_01,
            Man_WalkingJump_LH_2_02,
            Man_WalkingJump_LH_2_03,
            Man_WalkingJump_LH_2_04,
            Man_WalkingJump_LH_2_05,
            Man_WalkingJump_LH_2_06,
            Man_WalkingJump_LH_2_07,
            Man_WalkingJump_LH_2_08,
            
            Man_WalkingJump_LH_25_01,
            Man_WalkingJump_LH_25_02,
            Man_WalkingJump_LH_25_03,
            Man_WalkingJump_LH_25_04,
            Man_WalkingJump_LH_25_05,
            Man_WalkingJump_LH_25_06,
            Man_WalkingJump_LH_25_07,
            Man_WalkingJump_LH_25_08,
            Man_WalkingJump_LH_25_09,
            Man_WalkingJump_LH_25_10,
            Man_WalkingJump_LH_25_11,
            
            Man_WalkingJump_LH_1D_25_01,
            Man_WalkingJump_LH_1D_25_02,
            Man_WalkingJump_LH_1D_25_03,
            Man_WalkingJump_LH_1D_25_04,
            Man_WalkingJump_LH_1D_25_05,
            Man_WalkingJump_LH_1D_25_06,
            Man_WalkingJump_LH_1D_25_07,
            Man_WalkingJump_LH_1D_25_08,
            Man_WalkingJump_LH_1D_25_09,
            Man_WalkingJump_LH_1D_25_10,
            Man_WalkingJump_LH_1D_25_11,
            
            Man_WalkingJump_LH_2D_25_01,
            Man_WalkingJump_LH_2D_25_02,
            Man_WalkingJump_LH_2D_25_03,
            Man_WalkingJump_LH_2D_25_04,
            Man_WalkingJump_LH_2D_25_05,
            Man_WalkingJump_LH_2D_25_06,
            Man_WalkingJump_LH_2D_25_07,
            Man_WalkingJump_LH_2D_25_08,
            Man_WalkingJump_LH_2D_25_09,
            Man_WalkingJump_LH_2D_25_10,
            Man_WalkingJump_LH_2D_25_11,
            
            Man_WalkingJump_LH_UP_01,
            Man_WalkingJump_LH_UP_02,
            Man_WalkingJump_LH_UP_03,
            Man_WalkingJump_LH_UP_04,
            Man_WalkingJump_LH_UP_05,

            Man_Rope_Start_LH,

                Man_Rope_Start_LH_01 = Man_Rope_Start_LH,
                Man_Rope_Start_LH_02,
                Man_Rope_Start_LH_03,
                Man_Rope_Start_LH_04,
                Man_Rope_Start_LH_05,
                Man_Rope_Start_LH_06,
                Man_Rope_Start_LH_07,
                
                Man_Rope_End_LH_01,
                Man_Rope_End_LH_02,
                Man_Rope_End_LH_03,
                Man_Rope_End_LH_04,
                Man_Rope_End_LH_05,
                Man_Rope_End_LH_06,

            Man_Rope_End_LH = Man_Rope_End_LH_06,

            Man_BounceJump_LH_01,
            Man_BounceJump_LH_02,
            Man_BounceJump_LH_03,
            Man_BounceJump_LH_04,
            Man_BounceJump_LH_05,
            Man_BounceJump_LH_06,
            Man_BounceJump_LH_07,
            Man_BounceJump_LH_08,
            Man_BounceJump_LH_09,
            Man_BounceJump_LH_10,
            Man_BounceJump_LH_11,
            Man_BounceJump_LH_12,
            Man_BounceJump_LH_13,
            Man_BounceJump_LH_14,
            Man_BounceJump_LH_15,
            Man_BounceJump_LH_16,
            Man_BounceJump_LH_17,
            Man_BounceJump_LH_18,
            Man_BounceJump_LH_19,
            Man_BounceJump_LH_20,
            Man_BounceJump_LH_21,
            Man_BounceJump_LH_22,
            Man_BounceJump_LH_23,
            Man_BounceJump_LH_24,
            Man_BounceJump_LH_25,
            Man_BounceJump_LH_26,
            Man_BounceJump_LH_27,
            Man_BounceJump_LH_28,
            Man_BounceJump_LH_29,
            Man_BounceJump_LH_30,
            Man_BounceJump_LH_31,
            Man_BounceJump_LH_32,
            Man_BounceJump_LH_33,
            Man_BounceJump_LH_34,

            Man_Slide_LH_01,
            Man_Slide_LH_02,
            Man_Slide_LH_03,
            Man_Slide_LH_04,
            Man_Slide_LH_05,
            Man_Slide_LH_06,
            Man_Slide_LH_07,
            Man_Slide_LH_08,
            Man_Slide_LH_09,
            Man_Slide_LH_10,
            Man_Slide_LH_11,

            Man_Slide_LH_Full_01,
            Man_Slide_LH_Full_02,
            Man_Slide_LH_Full_03,
            Man_Slide_LH_Full_04,
            Man_Slide_LH_Full_05,
            Man_Slide_LH_Full_06,
            Man_Slide_LH_Full_07,
            Man_Slide_LH_Full_08,
            Man_Slide_LH_Full_09,
            Man_Slide_LH_Full_10,
            Man_Slide_LH_Full_11,
            Man_Slide_LH_Full_12,
            Man_Slide_LH_Full_13,

            Man_Slide_LH_Full_CanCont_01,       // Initial full slide that proceeds to a second full slide..
            Man_Slide_LH_Full_CanCont_02,
            Man_Slide_LH_Full_CanCont_03,
            Man_Slide_LH_Full_CanCont_04,
            Man_Slide_LH_Full_CanCont_05,
            Man_Slide_LH_Full_CanCont_06,
            Man_Slide_LH_Full_CanCont_07,
            Man_Slide_LH_Full_CanCont_08,
            Man_Slide_LH_Full_CanCont_09,
            Man_Slide_LH_Full_CanCont_10,
            Man_Slide_LH_Full_CanCont_11,
            Man_Slide_LH_Full_CanCont_12,
            Man_Slide_LH_Full_CanCont_13,

            Man_Slide_LH_Full_Cont_01,
            Man_Slide_LH_Full_Cont_02,
            Man_Slide_LH_Full_Cont_03,
            Man_Slide_LH_Full_Cont_04,
            Man_Slide_LH_Full_Cont_05,
            Man_Slide_LH_Full_Cont_06,
            Man_Slide_LH_Full_Cont_07,
            Man_Slide_LH_Full_Cont_08,

            Man_Slide_LH_Full_Land_01,
            Man_Slide_LH_Full_Land_02,
            Man_Slide_LH_Full_Land_03,
            Man_Slide_LH_Full_Land_04,
            Man_Slide_LH_Full_Land_05,
            Man_Slide_LH_Full_Land_06,
            Man_Slide_LH_Full_Land_07,
            Man_Slide_LH_Full_Land_08,
            Man_Slide_LH_Full_Land_09,
            Man_Slide_LH_Full_Land_10,
            Man_Slide_LH_Full_Land_11,
            Man_Slide_LH_Full_Land_12,
            Man_Slide_LH_Full_Land_13,

            Man_Hammering_LH_00,
            Man_Hammering_LH_01,
            Man_Hammering_LH_02,
            Man_Hammering_LH_03,
            Man_Hammering_LH_04,
            Man_Hammering_LH_05,
            Man_Hammering_LH_06,
            Man_Hammering_LH_07,
            Man_Hammering_LH_08,
            Man_Hammering_LH_09,
            Man_Hammering_LH_10,

            Man_Levering_LH_00,
            Man_Levering_LH_01,
            Man_Levering_LH_02,
            Man_Levering_LH_03,
            Man_Levering_LH_04,
            Man_Levering_LH_05,
            Man_Levering_LH_06,
            Man_Levering_LH_07,
            Man_Levering_LH_08,
            Man_Levering_LH_09,
            Man_Levering_LH_10,

            Man_Rollers_LH_01,
            Man_Rollers_LH_02,
            Man_Rollers_LH_03,
            Man_Rollers_LH_04,

            Man_Rollers_Stand_LH_01,
            Man_Rollers_Stand_LH_02,
            Man_Rollers_Stand_LH_03,
            Man_Rollers_Stand_LH_04,

            Man_Rollers_Fall_LH_01,
            Man_Rollers_Fall_LH_02,
            Man_Rollers_Fall_LH_03,
            Man_Rollers_Fall_LH_04,
            Man_Rollers_Fall_LH_05,

            Man_Vine_LH_01,
            Man_Vine_LH_02,
            Man_Vine_LH_03,
            Man_Vine_LH_04,
            Man_Vine_LH_05,
            Man_Vine_LH_06,
            Man_Vine_LH_07,
            Man_Vine_LH_08,
            Man_Vine_LH_09,
            Man_Vine_LH_10,
            Man_Vine_LH_11,
            Man_Vine_LH_12,
            Man_Vine_LH_13,
            Man_Vine_LH_14,
            Man_Vine_LH_15,
            Man_Vine_LH_16,
            Man_Vine_LH_17,
            Man_Vine_LH_18,
            Man_Vine_LH_19,
            Man_Vine_LH_20,

            Man_Vine_Start_LH,

                Man_Vine_Exit_LH_01 = Man_Vine_Start_LH,
                Man_Vine_Exit_LH_02,
                Man_Vine_Exit_LH_03,
                Man_Vine_Exit_LH_04,
                Man_Vine_Exit_LH_05,
                Man_Vine_Exit_LH_06,
                Man_Vine_Exit_LH_07,
                Man_Vine_Exit_LH_08,
                
                Man_Vine_Entry_LH_01,
                Man_Vine_Entry_LH_02,
                Man_Vine_Entry_LH_03,
                Man_Vine_Entry_LH_04,
                Man_Vine_Entry_LH_05,
                Man_Vine_Entry_LH_06,
                Man_Vine_Entry_LH_07,
                Man_Vine_Entry_LH_08,

            Man_Vine_End_LH = Man_Vine_Entry_LH_08,

            Man_Sword_Start_LH,

                Man_Sword_Stationary_LH = Man_Sword_Start_LH,

                Man_Sword_Lunge_LH_01,
                Man_Sword_Lunge_LH_02,
                Man_Sword_Lunge_LH_03,
                Man_Sword_Lunge_LH_04,
                Man_Sword_Lunge_LH_05,
                Man_Sword_Lunge_LH_06,

                Man_Sword_Walk_LH_01,
                Man_Sword_Walk_LH_02,
                Man_Sword_Walk_LH_03,
                Man_Sword_Walk_LH_04,

                Man_Sword_Walk_BK_LH_01,
                Man_Sword_Walk_BK_LH_02,
                Man_Sword_Walk_BK_LH_03,
                Man_Sword_Walk_BK_LH_04,

                Man_Sword_StandingJump_LH_01,
                Man_Sword_StandingJump_LH_02,
                Man_Sword_StandingJump_LH_03,
                Man_Sword_StandingJump_LH_04,
                Man_Sword_StandingJump_LH_05,
                Man_Sword_StandingJump_LH_06,
                Man_Sword_StandingJump_LH_07,

            Man_Sword_End_LH = Man_Sword_StandingJump_LH_07,

            Man_Die_Fire_LH_01,
            Man_Die_Fire_LH_02,
            Man_Die_Fire_LH_03,
            Man_Die_Fire_LH_04,
            Man_Die_Fire_LH_05,
            Man_Die_Fire_LH_06,
            Man_Die_Fire_LH_07,
            Man_Die_Fire_LH_08,
            Man_Die_Fire_LH_09,
            Man_Die_Fire_LH_10,
            Man_Die_Fire_LH_11,
            Man_Die_Fire_LH_12,

            Man_Die_Fire_Adj_LH_01,
            Man_Die_Fire_Adj_LH_02,

            Man_Die_Arrow_FallForward_LH_01,
            Man_Die_Arrow_FallForward_LH_02,
            Man_Die_Arrow_FallForward_LH_03,
            Man_Die_Arrow_FallForward_LH_04,

            Man_Die_Arrow_FallBackward_LH_01,
            Man_Die_Arrow_FallBackward_LH_02,
            Man_Die_Arrow_FallBackward_LH_03,
            Man_Die_Arrow_FallBackward_LH_04,

            Man_Die_Fall_LH_01,
            Man_Die_Fall_LH_02,
            Man_Die_Fall_LH_03,
            Man_Die_Fall_LH_04,

            Man_Die_FWD_LH_01,
            Man_Die_FWD_LH_02,
            Man_Die_FWD_LH_03,
            Man_Die_FWD_LH_04,

            Man_Die_BWD_LH_01,
            Man_Die_BWD_LH_02,
            Man_Die_BWD_LH_03,
            Man_Die_BWD_LH_04,

            Man_Die_Water_LH_01,
            Man_Die_Water_LH_02,
            Man_Die_Water_LH_03,
            Man_Die_Water_LH_04,
            Man_Die_Water_LH_05,
            Man_Die_Water_LH_06,
            Man_Die_Water_LH_07,

            Man_Die_Water_LH_02_01,
            Man_Die_Water_LH_02_02,
            Man_Die_Water_LH_02_03,
            Man_Die_Water_LH_02_04,
            Man_Die_Water_LH_02_05,
            Man_Die_Water_LH_02_06,
            Man_Die_Water_LH_02_07,

        Man_LH_End = Man_Die_Water_LH_02_07,
    
        Man_StandingJumpDown_RH_01,
        Man_StandingJumpDown_RH_02,
        Man_StandingJumpDown_RH_03,
        Man_StandingJumpDown_RH_04,
        Man_StandingJumpDown_RH_05,
        Man_StandingJumpDown_RH_06,
        Man_StandingJumpDown_RH_07,
        Man_StandingJumpDown_RH_08,
        Man_StandingJumpDown_RH_09,

    Man_End = Man_StandingJumpDown_RH_09,

    Enemy_Start = Man_End + 1,

        Enemy_RH_Start = Enemy_Start,

            Enemy_Walk_RH_00 = Enemy_RH_Start,
            Enemy_Walk_RH_01,
            Enemy_Walk_RH_02,
            Enemy_Walk_RH_03,

            Enemy_Walk_Bow_RH_00,
            Enemy_Walk_Bow_RH_01,
            Enemy_Walk_Bow_RH_02,
            Enemy_Walk_Bow_RH_03,

            Enemy_Fire_RH_00,
            Enemy_Fire_RH_01,
            Enemy_Fire_RH_02,
            Enemy_Fire_RH_03,
            Enemy_Fire_RH_04,
            Enemy_Fire_RH_05,
            Enemy_Fire_RH_06,
            Enemy_Fire_RH_07,
            Enemy_Fire_RH_08,
            Enemy_Fire_RH_09,
            Enemy_Fire_RH_10,
            Enemy_Fire_RH_11,
            Enemy_Fire_RH_12,

            Enemy_Trebochet_Release_RH_01,
            Enemy_Trebochet_Release_RH_02,
            Enemy_Trebochet_Release_RH_03,
            Enemy_Trebochet_Release_RH_04,
            Enemy_Trebochet_Release_RH_05,
            Enemy_Trebochet_Release_RH_06,
            Enemy_Trebochet_Release_RH_07,
            Enemy_Trebochet_Release_RH_08,
            Enemy_Trebochet_Release_RH_09,
            Enemy_Trebochet_Release_RH_10,
            Enemy_Trebochet_Release_RH_11,
            Enemy_Trebochet_Release_RH_12,
            Enemy_Trebochet_Release_RH_13,
            Enemy_Trebochet_Release_RH_14,

            Enemy_Sword_Start_RH,

                Enemy_Sword_Stationary_RH =  Enemy_Sword_Start_RH,

                Enemy_Sword_Lunge_RH_01,
                Enemy_Sword_Lunge_RH_02,
                Enemy_Sword_Lunge_RH_03,
                Enemy_Sword_Lunge_RH_04,
                Enemy_Sword_Lunge_RH_05,
                Enemy_Sword_Lunge_RH_06,

                Enemy_Sword_Walk_RH_01,
                Enemy_Sword_Walk_RH_02,
                Enemy_Sword_Walk_RH_03,
                Enemy_Sword_Walk_RH_04,

                Enemy_Sword_Walk_BK_RH_01,
                Enemy_Sword_Walk_BK_RH_02,
                Enemy_Sword_Walk_BK_RH_03,
                Enemy_Sword_Walk_BK_RH_04,

                Enemy_Sword_StandingJump_RH_01,
                Enemy_Sword_StandingJump_RH_02,
                Enemy_Sword_StandingJump_RH_03,
                Enemy_Sword_StandingJump_RH_04,
                Enemy_Sword_StandingJump_RH_05,
                Enemy_Sword_StandingJump_RH_06,
                Enemy_Sword_StandingJump_RH_07,
                
            Enemy_Sword_End_RH =  Enemy_Sword_StandingJump_RH_07,

        Enemy_RH_End = Enemy_Sword_End_RH,

        Enemy_LH_Start = Enemy_RH_End + 1,

            Enemy_Walk_LH_00 = Enemy_LH_Start,
            Enemy_Walk_LH_01,
            Enemy_Walk_LH_02,
            Enemy_Walk_LH_03,

            Enemy_Walk_Bow_LH_00,
            Enemy_Walk_Bow_LH_01,
            Enemy_Walk_Bow_LH_02,
            Enemy_Walk_Bow_LH_03,

            Enemy_Fire_LH_00,
            Enemy_Fire_LH_01,
            Enemy_Fire_LH_02,
            Enemy_Fire_LH_03,
            Enemy_Fire_LH_04,
            Enemy_Fire_LH_05,
            Enemy_Fire_LH_06,
            Enemy_Fire_LH_07,
            Enemy_Fire_LH_08,
            Enemy_Fire_LH_09,
            Enemy_Fire_LH_10,
            Enemy_Fire_LH_11,
            Enemy_Fire_LH_12,

            Enemy_Trebochet_Release_LH_01,
            Enemy_Trebochet_Release_LH_02,
            Enemy_Trebochet_Release_LH_03,
            Enemy_Trebochet_Release_LH_04,
            Enemy_Trebochet_Release_LH_05,
            Enemy_Trebochet_Release_LH_06,
            Enemy_Trebochet_Release_LH_07,
            Enemy_Trebochet_Release_LH_08,
            Enemy_Trebochet_Release_LH_09,
            Enemy_Trebochet_Release_LH_10,
            Enemy_Trebochet_Release_LH_11,
            Enemy_Trebochet_Release_LH_12,
            Enemy_Trebochet_Release_LH_13,
            Enemy_Trebochet_Release_LH_14,

            Enemy_Sword_Start_LH,

                Enemy_Sword_Stationary_LH =  Enemy_Sword_Start_LH,

                Enemy_Sword_Lunge_LH_01,
                Enemy_Sword_Lunge_LH_02,
                Enemy_Sword_Lunge_LH_03,
                Enemy_Sword_Lunge_LH_04,
                Enemy_Sword_Lunge_LH_05,
                Enemy_Sword_Lunge_LH_06,

                Enemy_Sword_Walk_LH_01,
                Enemy_Sword_Walk_LH_02,
                Enemy_Sword_Walk_LH_03,
                Enemy_Sword_Walk_LH_04,

                Enemy_Sword_Walk_BK_LH_01,
                Enemy_Sword_Walk_BK_LH_02,
                Enemy_Sword_Walk_BK_LH_03,
                Enemy_Sword_Walk_BK_LH_04,

                Enemy_Sword_StandingJump_LH_01,
                Enemy_Sword_StandingJump_LH_02,
                Enemy_Sword_StandingJump_LH_03,
                Enemy_Sword_StandingJump_LH_04,
                Enemy_Sword_StandingJump_LH_05,
                Enemy_Sword_StandingJump_LH_06,
                Enemy_Sword_StandingJump_LH_07,
                
            Enemy_Sword_End_LH =  Enemy_Sword_StandingJump_LH_07,

        Enemy_LH_End = Enemy_Sword_End_LH,

        Enemy_Die_FWD_LH_01,
        Enemy_Die_FWD_LH_02,
        Enemy_Die_FWD_LH_03,
        Enemy_Die_FWD_LH_04,
        Enemy_Die_FWD_LH_05,
        Enemy_Die_FWD_LH_06,
        Enemy_Die_FWD_LH_07,
        Enemy_Die_FWD_LH_08,
        Enemy_Die_FWD_LH_09,
        Enemy_Die_FWD_LH_10,
        Enemy_Die_FWD_LH_11,
        Enemy_Die_FWD_LH_12,
        Enemy_Die_FWD_LH_13,
        Enemy_Die_BWD_LH_01,
        Enemy_Die_BWD_LH_02,
        Enemy_Die_BWD_LH_03,
        Enemy_Die_BWD_LH_04,
        Enemy_Die_BWD_LH_05,
        Enemy_Die_BWD_LH_06,
        Enemy_Die_BWD_LH_07,
        Enemy_Die_BWD_LH_08,
        Enemy_Die_BWD_LH_09,
        Enemy_Die_BWD_LH_10,
        Enemy_Die_BWD_LH_11,
        Enemy_Die_BWD_LH_12,
        Enemy_Die_BWD_LH_13,
        Enemy_Die_FWD_RH_01,
        Enemy_Die_FWD_RH_02,
        Enemy_Die_FWD_RH_03,
        Enemy_Die_FWD_RH_04,
        Enemy_Die_FWD_RH_05,
        Enemy_Die_FWD_RH_06,
        Enemy_Die_FWD_RH_07,
        Enemy_Die_FWD_RH_08,
        Enemy_Die_FWD_RH_09,
        Enemy_Die_FWD_RH_10,
        Enemy_Die_FWD_RH_11,
        Enemy_Die_FWD_RH_12,
        Enemy_Die_FWD_RH_13,
        Enemy_Die_BWD_RH_01,
        Enemy_Die_BWD_RH_02,
        Enemy_Die_BWD_RH_03,
        Enemy_Die_BWD_RH_04,
        Enemy_Die_BWD_RH_05,
        Enemy_Die_BWD_RH_06,
        Enemy_Die_BWD_RH_07,
        Enemy_Die_BWD_RH_08,
        Enemy_Die_BWD_RH_09,
        Enemy_Die_BWD_RH_10,
        Enemy_Die_BWD_RH_11,
        Enemy_Die_BWD_RH_12,
        Enemy_Die_BWD_RH_13,

    Enemy_End,

    None,

};

inline Stance &operator++(Stance &c) {
    c = static_cast<Stance>( static_cast<uint8_t>(c) + 1 );
    return c;
}

inline Stance operator++(Stance &c, int) {
    Stance result = c;
    ++c;
    return result;
}


enum class GameState : uint8_t {

    SplashScreen_Start,
        SplashScreen_00 = SplashScreen_Start,
        SplashScreen_01,
        SplashScreen_02,
        SplashScreen_03,
    SplashScreen_End,

    Title_Init,
    Title_Start,
        Title_OptPlay,
        Title_OptSound,
        Title_OptCredits,
        Title_OptResume,
        Title_OptPlay2,
        Title_OptSound2,
        Title_OptSound_Music,
        Title_OptSound_SFX,
        Title_OptSound_Volume,
        Title_OptSound_Music2,
        Title_OptSound_SFX2,
        Title_OptSound_Volume2,
        Title_ShowCredits,
    Title_End,

    Play_Init,
    Play_Start,
        Play_BoatEnters,
        Play_PlayerJumps,
        Play_PlayerCenters,
        Play,
        Play_Battle,
        Play_Dead,
    Play_End,
    Play_Game_Init,
    PlayGame_Start,
        Play_Game,
        Inventory_Open,
        Inventory_Open_More_Reset,
        Inventory_Open_More_Exit,
        Inventory_Open_Reset_0,
        Inventory_Open_Reset_1,
        Inventory_Open_Reset_Exit_0,
        Inventory_Open_Reset_Exit_1,
        Inventory_Open_Exit_0,
        Inventory_Open_Exit_1,
        Chakana_Open,
    PlayGame_End,

    Play_Gamble_Start,
        Play_Gamble_Select_Open = Play_Gamble_Start,
        Play_Gamble_Select_Exit,
        Play_Gamble_Select_Play,
        Play_Gamble_Select_Spin,
        Play_Gamble_Select_Win,
        Play_Gamble_Select_Lose,
    Play_Gamble_End = Play_Gamble_Select_Lose,

    #ifdef MAP_SHOW_PORTS_VISITED    
        Map_Init,
        Map,
        Map_ShowDialogue,
        Map_ShowMenu_1,
        Map_ShowMenu_2,
        Map_ShowMenu_3,
        Map_ShowMenu_4,
        Map_ShowMenu_Back,
        Map_ShowMenu_Exit,
        Map_MoveBoat,
    #else
        Map_Init,
        Map,
        Map_ShowDialogue,
        Map_ShowMenu,
        Map_ShowMenu_Back,
        Map_ShowMenu_Exit,
        Map_MoveBoat,
    #endif
};

inline GameState &operator++(GameState &c) {
  c = static_cast<GameState>( static_cast<uint8_t>(c) + 1 );
  return c;
}

inline GameState operator++(GameState &c, int) {
  GameState result = c;
  ++c;
  return result;
}

inline GameState &operator--( GameState & c ) {
  c = static_cast<GameState>( static_cast<uint8_t>(c) - 1 );
  return c;
};

inline GameState operator--( GameState & c, int ) {
  GameState result = c;
  --c;
  return result;
};


namespace Constants {

	constexpr uint16_t Player_Stance_Offset = Stance::Man_LH_Start - Stance::Man_RH_Start;

};


