#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xf381;
constexpr uint24_t FX_DATA_BYTES = 814796;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x000BC2;
  constexpr uint24_t SFX_Victory = 0x000C66;
  constexpr uint24_t SFX_XPGain = 0x000D1A;
  constexpr uint24_t SFX_Three_Inc = 0x000D2E;
  constexpr uint24_t SFX_Three_Dec = 0x000D4A;
  constexpr uint24_t SFX_PlayerBlip = 0x000D66;
  constexpr uint24_t SFX_EnemyBlip = 0x000D76;
  constexpr uint24_t SFX_Explosion = 0x000D86;
  constexpr uint24_t SFX_DoubleBeep = 0x000DCA;
  constexpr uint24_t SFX_DoubleBeepDown = 0x000DDA;
  constexpr uint24_t SFX_Bet1 = 0x000DEA;
  constexpr uint24_t SFX_Bet2 = 0x000DF2;
  constexpr uint24_t SFX_Bet3 = 0x000DFA;
  constexpr uint24_t SFX_Bet4 = 0x000E02;
  constexpr uint24_t SFX_Bet5 = 0x000E0A;
  constexpr uint24_t SFX_Bet6 = 0x000E12;
  constexpr uint24_t SFX_Click = 0x000E1A;
  constexpr uint24_t SFX_SmallBlind = 0x000E22;
  constexpr uint24_t SFX_BigBlind = 0x000E2A;
  constexpr uint24_t Songs = 0x000E3A;
  constexpr uint24_t SFXs = 0x000E3D;
}

namespace Constants
{
  constexpr uint24_t TrebochetImgs = 0x000E76;
  constexpr uint24_t mapCoords = 0x000E84;
  constexpr uint24_t portNames_Coords = 0x000EBC;
  constexpr uint24_t BeachDetails = 0x000EF4;
  constexpr uint24_t PortCosts = 0x000F48;
  constexpr uint24_t StanceImgIdx = 0x001029;
  constexpr uint24_t StanceY = 0x001433;
  constexpr uint24_t xForeground = 0x00183D;
  constexpr uint24_t xMiddleground = 0x001C47;
  constexpr uint24_t xBackground = 0x002051;
  constexpr uint24_t subsititueStance = 0x00245B;
  constexpr uint24_t swingyThing_X = 0x002C6F;
  constexpr uint24_t swingyThing_Y = 0x002C7F;
  constexpr uint24_t Ball_X = 0x002C8F;
  constexpr uint24_t Ball_Y = 0x002CA3;
  constexpr uint24_t SwordLunge_Player = 0x002CB7;
  constexpr uint24_t SwordLunge_Enemy = 0x002CCD;
}

namespace Constants
{
  constexpr uint24_t BoatMovements = 0x002CE3;
  constexpr uint24_t BoatCoords_00_AC = 0x002D0D;
  constexpr uint24_t BoatCoords_00_CW = 0x002D9D;
  constexpr uint24_t BoatCoords_01_AC = 0x002E66;
  constexpr uint24_t BoatCoords_01_CW = 0x002EBA;
  constexpr uint24_t BoatCoords_02_AC = 0x002F1D;
  constexpr uint24_t BoatCoords_02_CW = 0x002F80;
  constexpr uint24_t BoatCoords_03_AC = 0x003043;
  constexpr uint24_t BoatCoords_04_AC = 0x0030E8;
  constexpr uint24_t BoatCoords_04_CW = 0x0031BA;
  constexpr uint24_t BoatCoords_05_AC = 0x003268;
  constexpr uint24_t BoatCoords_06_AC = 0x0032BF;
  constexpr uint24_t BoatCoords_06_CW = 0x003370;
  constexpr uint24_t BoatCoords_07_AC = 0x0033F4;
  constexpr uint24_t BoatCoords_07_CW = 0x003475;
  constexpr uint24_t BoatCoords_08_AC = 0x0034DE;
  constexpr uint24_t BoatCoords_08_CW = 0x003586;
  constexpr uint24_t BoatCoords = 0x00360A;
  constexpr uint24_t BoatCoords_Start = 0x003640;
}

namespace Images
{
  constexpr uint24_t Numbers_5x3_2D_BW = 0x003688;
  constexpr uint24_t Numbers_5x3_3D_BW = 0x003EBE;
  constexpr uint24_t Numbers_6x4_3D_BW = 0x006044;
  constexpr uint24_t Numbers_6x4_3D_WB = 0x009106;
  constexpr uint24_t Chakana = 0x00C1C8;
  constexpr uint24_t PPOT = 0x00FDCA;
  constexpr uint24_t Sound_Volume_Grey = 0x012DCC;
  constexpr uint24_t Sound_Volume_White = 0x01360E;
  constexpr uint24_t Sound_Checkbox = 0x013E50;
  constexpr uint24_t Title_Base = 0x013E5E;
  constexpr uint24_t Title_Options = 0x016E60;
  constexpr uint24_t Pause = 0x01BAE2;
  constexpr uint24_t HUD_BW = 0x01D2E4;
  constexpr uint24_t HUD_WB = 0x0209A6;
  constexpr uint24_t PortNames = 0x022268;
  constexpr uint24_t PortNames_WB = 0x022780;
  constexpr uint24_t ArrowUpDown = 0x023106;
  constexpr uint24_t Palm1 = 0x023117;
  constexpr uint24_t Palm2 = 0x023701;
  constexpr uint24_t Palm3 = 0x023BCB;
  constexpr uint24_t Palm4 = 0x02416D;
  constexpr uint24_t Palm5 = 0x024613;
  constexpr uint24_t Palm6 = 0x024735;
  constexpr uint24_t Background = 0x02488D;
  constexpr uint24_t Background_Above = 0x02548F;
  constexpr uint24_t Player = 0x025611;
  constexpr uint24_t Enemy = 0x02C213;
  constexpr uint24_t Player_Bounce = 0x030A15;
  constexpr uint24_t Waves = 0x030C57;
  constexpr uint24_t Pulse = 0x031559;
  constexpr uint24_t Beach = 0x03275B;
  constexpr uint24_t Beach_LH = 0x032775;
  constexpr uint24_t Boat = 0x033587;
  constexpr uint24_t Boat_Small = 0x0344B9;
  constexpr uint24_t Arrow = 0x03487B;
  constexpr uint24_t InventoryPanel = 0x034901;
  constexpr uint24_t InventoryPanel_Cursor = 0x037903;
  constexpr uint24_t Cursor_00 = 0x037A19;
  constexpr uint24_t Cursor_01 = 0x037A51;
  constexpr uint24_t Item_00 = 0x037A89;
  constexpr uint24_t Item_01 = 0x03808B;
  constexpr uint24_t Item_02 = 0x03868D;
  constexpr uint24_t Item_03 = 0x038BCF;
  constexpr uint24_t Item_04 = 0x0391D1;
  constexpr uint24_t Item_05 = 0x039413;
  constexpr uint24_t Item_06 = 0x039A15;
  constexpr uint24_t Item_07 = 0x03A017;
  constexpr uint24_t Item_08 = 0x03A619;
  constexpr uint24_t Item_09 = 0x03AC1B;
  constexpr uint24_t Item_09a = 0x03AFDD;
  constexpr uint24_t Item_10 = 0x03B01B;
  constexpr uint24_t Item_11 = 0x03B6DD;
  constexpr uint24_t Item_12 = 0x03BCDF;
  constexpr uint24_t Item_13 = 0x03EE61;
  constexpr uint24_t Item_14 = 0x03F2E3;
  constexpr uint24_t Item_15 = 0x0401E5;
  constexpr uint24_t Item_16 = 0x0410E7;
  constexpr uint24_t Item_17 = 0x0428E9;
  constexpr uint24_t Item_18 = 0x042EEB;
  constexpr uint24_t Item_19 = 0x0437ED;
  constexpr uint24_t Item_20 = 0x0443EF;
  constexpr uint24_t Item_21 = 0x044B71;
  constexpr uint24_t Item_21_Action_LH = 0x045473;
  constexpr uint24_t Item_21_Action_RH = 0x048D75;
  constexpr uint24_t Item_22 = 0x04D4B7;
  constexpr uint24_t Map = 0x04DAB9;
  constexpr uint24_t Scroll = 0x05B2BB;
  constexpr uint24_t Scroll_Map = 0x05F1BD;
  constexpr uint24_t Crate_00 = 0x06AEBF;
  constexpr uint24_t Crate_01 = 0x06AF81;
  constexpr uint24_t Crate_01_02 = 0x06B043;
  constexpr uint24_t Crate_01_03 = 0x06B1C5;
  constexpr uint24_t Crate_01_04 = 0x06B407;
  constexpr uint24_t Crate_02 = 0x06B709;
  constexpr uint24_t Crate_03 = 0x06B7CB;
  constexpr uint24_t Crate_04 = 0x06B88D;
  constexpr uint24_t Crate_05 = 0x06B94F;
  constexpr uint24_t Crate_06 = 0x06BA11;
  constexpr uint24_t Crate_07 = 0x06BAD3;
  constexpr uint24_t Crate_08 = 0x06BB95;
  constexpr uint24_t Crate_09 = 0x06BC57;
  constexpr uint24_t Crate_10 = 0x06BD19;
  constexpr uint24_t Crate_11 = 0x06BDDB;
  constexpr uint24_t Crate_11a = 0x06BE9D;
  constexpr uint24_t Crate_12 = 0x06BF5F;
  constexpr uint24_t Crate_13 = 0x06C021;
  constexpr uint24_t Crate_14 = 0x06C0E3;
  constexpr uint24_t Crate_15 = 0x06C1A5;
  constexpr uint24_t Crate_16 = 0x06C267;
  constexpr uint24_t Crate_17 = 0x06C329;
  constexpr uint24_t Crate_18 = 0x06C3EB;
  constexpr uint24_t Crate_19 = 0x06C4AD;
  constexpr uint24_t Crate_20 = 0x06C56F;
  constexpr uint24_t Crate_21 = 0x06C631;
  constexpr uint24_t Crate_22 = 0x06C6F3;
  constexpr uint24_t Crate_23 = 0x06C7B5;
  constexpr uint24_t Crate_24 = 0x06C877;
  constexpr uint24_t Crate_25 = 0x06C939;
  constexpr uint24_t Crate_26 = 0x06C9FB;
  constexpr uint24_t Crate_27 = 0x06CABD;
  constexpr uint24_t Crate_28 = 0x06CB7F;
  constexpr uint24_t Crate_29 = 0x06CC41;
  constexpr uint24_t Crate_30 = 0x06CD03;
  constexpr uint24_t Crate_31 = 0x06CDC5;
  constexpr uint24_t Crate_32 = 0x06CE87;
  constexpr uint24_t Crate_33 = 0x06D189;
  constexpr uint24_t Crate_34 = 0x06D48B;
  constexpr uint24_t Crate_35 = 0x06D78D;
  constexpr uint24_t Crate_36 = 0x06DA8F;
  constexpr uint24_t Crate_37 = 0x06DB51;
  constexpr uint24_t Crate_38 = 0x06DC13;
  constexpr uint24_t Crate_39 = 0x06DCD5;
  constexpr uint24_t Crate_40 = 0x06E8D7;
  constexpr uint24_t Crate_41 = 0x06F4D9;
  constexpr uint24_t Spikes_Top = 0x0700DB;
  constexpr uint24_t Spikes_Bottom = 0x07019D;
  constexpr uint24_t Trebochet_Ball = 0x07025F;
  constexpr uint24_t Health = 0x070FE1;
  constexpr uint24_t Glint = 0x071583;
  constexpr uint24_t Sword_Wound = 0x071B85;
  constexpr uint24_t BoatEnters = 0x071DC7;
  constexpr uint24_t EndOfLevel = 0x0BC1C9;
  constexpr uint24_t PalmImages = 0x0C69CB;
  constexpr uint24_t ItemsIndex = 0x0C69E3;
  constexpr uint24_t InventoryFrame = 0x0C6AA0;
}

namespace Levels
{
  constexpr uint24_t Level_00 = 0x0C6ADF;
  constexpr uint24_t Level_00_Items = 0x0C6DFF;
  constexpr uint24_t Level_00_Enemies = 0x0C6E2F;
  constexpr uint24_t Level_00_PlayerStart = 0x0C6E57;
  constexpr uint24_t Levels = 0x0C6E5D;
  constexpr uint24_t Level_Items = 0x0C6E7B;
  constexpr uint24_t Level_Enemies = 0x0C6E96;
  constexpr uint24_t Level_PlayerStart = 0x0C6EB1;
}

