#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xf16f;
constexpr uint24_t FX_DATA_BYTES = 950361;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x000BC2;
  constexpr uint24_t SFX_Victory = 0x000C66;
  constexpr uint24_t SFX_XPGain = 0x000D1A;
  constexpr uint24_t SFX_Three_Inc = 0x000D2E;
  constexpr uint24_t SFX_Three_Dec = 0x000D4A;
  constexpr uint24_t SFX_PlayerBlip = 0x000D66;
  constexpr uint24_t SFX_EnemyBlip = 0x000D76;
  constexpr uint24_t SFX_Explosion = 0x000D86;
  constexpr uint24_t SFX_DoubleBeep = 0x000DCA;
  constexpr uint24_t SFX_DoubleBeepDown = 0x000DDA;
  constexpr uint24_t SFX_Bet1 = 0x000DEA;
  constexpr uint24_t SFX_Bet2 = 0x000DF2;
  constexpr uint24_t SFX_Bet3 = 0x000DFA;
  constexpr uint24_t SFX_Bet4 = 0x000E02;
  constexpr uint24_t SFX_Bet5 = 0x000E0A;
  constexpr uint24_t SFX_Bet6 = 0x000E12;
  constexpr uint24_t SFX_Click = 0x000E1A;
  constexpr uint24_t SFX_SmallBlind = 0x000E22;
  constexpr uint24_t SFX_BigBlind = 0x000E2A;
  constexpr uint24_t Songs = 0x000E3A;
  constexpr uint24_t SFXs = 0x000E3D;
}

namespace Constants
{
  constexpr uint24_t InventoryCursorY = 0x000E76;
  constexpr uint24_t GambleFrames = 0x000E7C;
  constexpr uint24_t TrebochetImgs = 0x000F4C;
  constexpr uint24_t mapCoords = 0x000F5A;
  constexpr uint24_t portNames_Coords = 0x000F92;
  constexpr uint24_t BeachDetails = 0x000FCA;
  constexpr uint24_t PortCosts = 0x00101E;
  constexpr uint24_t StanceImgIdx = 0x001367;
  constexpr uint24_t SubsititueStance = 0x001771;
  constexpr uint24_t StanceDetails = 0x001F85;
  constexpr uint24_t swingyThing_X = 0x002FAD;
  constexpr uint24_t swingyThing_Y = 0x002FBD;
  constexpr uint24_t Ball_X = 0x002FCD;
  constexpr uint24_t Ball_Y = 0x002FE1;
  constexpr uint24_t SwordLunge_Player = 0x002FF5;
  constexpr uint24_t SwordLunge_Enemy = 0x00300B;
}

namespace Constants
{
  constexpr uint24_t BoatMovements = 0x003021;
  constexpr uint24_t BoatCoords_00_AC = 0x00304B;
  constexpr uint24_t BoatCoords_00_CW = 0x0030DB;
  constexpr uint24_t BoatCoords_01_AC = 0x0031A4;
  constexpr uint24_t BoatCoords_01_CW = 0x0031F8;
  constexpr uint24_t BoatCoords_02_AC = 0x00325B;
  constexpr uint24_t BoatCoords_02_CW = 0x0032BE;
  constexpr uint24_t BoatCoords_03_AC = 0x003381;
  constexpr uint24_t BoatCoords_04_AC = 0x003426;
  constexpr uint24_t BoatCoords_04_CW = 0x0034F8;
  constexpr uint24_t BoatCoords_05_AC = 0x0035A6;
  constexpr uint24_t BoatCoords_06_AC = 0x0035FD;
  constexpr uint24_t BoatCoords_06_CW = 0x0036AE;
  constexpr uint24_t BoatCoords_07_AC = 0x003732;
  constexpr uint24_t BoatCoords_07_CW = 0x0037B3;
  constexpr uint24_t BoatCoords_08_AC = 0x00381C;
  constexpr uint24_t BoatCoords_08_CW = 0x0038C4;
  constexpr uint24_t BoatCoords = 0x003948;
  constexpr uint24_t BoatCoords_Start = 0x00397E;
}

namespace Images
{
  constexpr uint24_t Numbers_5x3_2D_BW = 0x0039C6;
  constexpr uint24_t Numbers_5x3_3D_BW = 0x0041FC;
  constexpr uint24_t Numbers_6x4_3D_BW = 0x006382;
  constexpr uint24_t Numbers_6x4_2D_BW = 0x009444;
  constexpr uint24_t Numbers_6x4_3D_WB = 0x009ED2;
  constexpr uint24_t PPOT = 0x00CF94;
  constexpr uint24_t Sound_Volume_Grey = 0x00FF96;
  constexpr uint24_t Sound_Volume_White = 0x0107D8;
  constexpr uint24_t Sound_Checkbox = 0x01101A;
  constexpr uint24_t Title_Base = 0x011028;
  constexpr uint24_t Title_Options = 0x01402A;
  constexpr uint24_t Pause = 0x018CAC;
  constexpr uint24_t BoatEnters = 0x01A4AE;
  constexpr uint24_t PortNames = 0x0648B0;
  constexpr uint24_t PortNames_WB = 0x064DC8;
  constexpr uint24_t Map = 0x0660D2;
  constexpr uint24_t Scroll_Map = 0x0738D4;
  constexpr uint24_t GamblePanel = 0x0834D6;
  constexpr uint24_t Scroll = 0x0888D8;
  constexpr uint24_t Chakana = 0x08C7DA;
  constexpr uint24_t ArrowUpDown = 0x0903DC;
  constexpr uint24_t Spikes_Top = 0x0903ED;
  constexpr uint24_t Spikes_Bottom = 0x0904AF;
  constexpr uint24_t Trebochet_Ball = 0x090571;
  constexpr uint24_t Health = 0x0912F3;
  constexpr uint24_t Glint = 0x091895;
  constexpr uint24_t Sword_Wound = 0x091E97;
  constexpr uint24_t EndOfLevel = 0x0920D9;
  constexpr uint24_t EndOfLife = 0x09C8DB;
  constexpr uint24_t Palm1 = 0x0B18DD;
  constexpr uint24_t Palm2 = 0x0B1EC7;
  constexpr uint24_t Palm3 = 0x0B2391;
  constexpr uint24_t Palm4 = 0x0B2933;
  constexpr uint24_t Palm5 = 0x0B2DD9;
  constexpr uint24_t Palm6 = 0x0B2EFB;
  constexpr uint24_t Background = 0x0B3053;
  constexpr uint24_t Background_Above = 0x0B3C55;
  constexpr uint24_t Player = 0x0B3DD7;
  constexpr uint24_t Enemy = 0x0BA9D9;
  constexpr uint24_t Player_Bounce = 0x0BF1DB;
  constexpr uint24_t Waves = 0x0BF41D;
  constexpr uint24_t Pulse = 0x0BFD1F;
  constexpr uint24_t Beach = 0x0C0F21;
  constexpr uint24_t Beach_LH = 0x0C0F53;
  constexpr uint24_t Boat = 0x0C1D65;
  constexpr uint24_t Boat_Small = 0x0C2C97;
  constexpr uint24_t Arrow = 0x0C3059;
  constexpr uint24_t Hearts = 0x0C30DF;
  constexpr uint24_t InventoryPanel = 0x0C317A;
  constexpr uint24_t InventoryPanel_Cursor = 0x0CC17C;
  constexpr uint24_t Cursor_00 = 0x0CC292;
  constexpr uint24_t Cursor_01 = 0x0CC2CA;
  constexpr uint24_t Item_00 = 0x0CC302;
  constexpr uint24_t Item_01 = 0x0CC904;
  constexpr uint24_t Item_02 = 0x0CCF06;
  constexpr uint24_t Item_03 = 0x0CD448;
  constexpr uint24_t Item_04 = 0x0CDA4A;
  constexpr uint24_t Item_05 = 0x0CDC8C;
  constexpr uint24_t Item_06 = 0x0CE28E;
  constexpr uint24_t Item_07 = 0x0CE890;
  constexpr uint24_t Item_08 = 0x0CEE92;
  constexpr uint24_t Item_09 = 0x0CF494;
  constexpr uint24_t Item_09a = 0x0CF856;
  constexpr uint24_t Item_10 = 0x0CF894;
  constexpr uint24_t Item_11 = 0x0CFF56;
  constexpr uint24_t Item_12 = 0x0D0558;
  constexpr uint24_t Item_13 = 0x0D36DA;
  constexpr uint24_t Item_14 = 0x0D3B5C;
  constexpr uint24_t Item_15 = 0x0D4A5E;
  constexpr uint24_t Item_16 = 0x0D5960;
  constexpr uint24_t Item_17 = 0x0D7162;
  constexpr uint24_t Item_18 = 0x0D7764;
  constexpr uint24_t Item_19 = 0x0D8066;
  constexpr uint24_t Item_20 = 0x0D8C68;
  constexpr uint24_t Item_21 = 0x0D93EA;
  constexpr uint24_t Item_21_Action_LH = 0x0D9CEC;
  constexpr uint24_t Item_21_Action_RH = 0x0DD5EE;
  constexpr uint24_t Item_22 = 0x0E1D30;
  constexpr uint24_t Item_23 = 0x0E2332;
  constexpr uint24_t Crate_00 = 0x0E2934;
  constexpr uint24_t Crate_01 = 0x0E29F6;
  constexpr uint24_t Crate_01_02 = 0x0E2AB8;
  constexpr uint24_t Crate_01_03 = 0x0E2C3A;
  constexpr uint24_t Crate_01_04 = 0x0E2E7C;
  constexpr uint24_t Crate_02 = 0x0E317E;
  constexpr uint24_t Crate_03 = 0x0E3240;
  constexpr uint24_t Crate_04 = 0x0E3302;
  constexpr uint24_t Crate_05 = 0x0E33C4;
  constexpr uint24_t Crate_06 = 0x0E3486;
  constexpr uint24_t Crate_07 = 0x0E3548;
  constexpr uint24_t Crate_08 = 0x0E360A;
  constexpr uint24_t Crate_09 = 0x0E36CC;
  constexpr uint24_t Crate_10 = 0x0E378E;
  constexpr uint24_t Crate_11 = 0x0E3850;
  constexpr uint24_t Crate_11a = 0x0E3912;
  constexpr uint24_t Crate_12 = 0x0E39D4;
  constexpr uint24_t Crate_13 = 0x0E3A96;
  constexpr uint24_t Crate_14 = 0x0E3B58;
  constexpr uint24_t Crate_15 = 0x0E3C1A;
  constexpr uint24_t Crate_16 = 0x0E3CDC;
  constexpr uint24_t Crate_17 = 0x0E3D9E;
  constexpr uint24_t Crate_18 = 0x0E3E60;
  constexpr uint24_t Crate_19 = 0x0E3F22;
  constexpr uint24_t Crate_20 = 0x0E3FE4;
  constexpr uint24_t Crate_21 = 0x0E40A6;
  constexpr uint24_t Crate_22 = 0x0E4168;
  constexpr uint24_t Crate_23 = 0x0E422A;
  constexpr uint24_t Crate_24 = 0x0E42EC;
  constexpr uint24_t Crate_25 = 0x0E43AE;
  constexpr uint24_t Crate_26 = 0x0E4470;
  constexpr uint24_t Crate_27 = 0x0E4532;
  constexpr uint24_t Crate_28 = 0x0E45F4;
  constexpr uint24_t Crate_29 = 0x0E46B6;
  constexpr uint24_t Crate_30 = 0x0E4778;
  constexpr uint24_t Crate_31 = 0x0E483A;
  constexpr uint24_t Crate_32 = 0x0E48FC;
  constexpr uint24_t Crate_33 = 0x0E4BFE;
  constexpr uint24_t Crate_34 = 0x0E4F00;
  constexpr uint24_t Crate_35 = 0x0E5202;
  constexpr uint24_t Crate_36 = 0x0E5504;
  constexpr uint24_t Crate_37 = 0x0E55C6;
  constexpr uint24_t Crate_38 = 0x0E5688;
  constexpr uint24_t Crate_39 = 0x0E574A;
  constexpr uint24_t Crate_40 = 0x0E634C;
  constexpr uint24_t Crate_41 = 0x0E6F4E;
  constexpr uint24_t PalmImages = 0x0E7B50;
  constexpr uint24_t ItemsIndex = 0x0E7B68;
  constexpr uint24_t InventoryFrame = 0x0E7C2B;
}

namespace Levels
{
  constexpr uint24_t Level_00 = 0x0E7C6C;
  constexpr uint24_t Level_00_Items = 0x0E7F8C;
  constexpr uint24_t Level_00_Enemies = 0x0E7FBC;
  constexpr uint24_t Level_00_PlayerStart = 0x0E7FE4;
  constexpr uint24_t Levels = 0x0E7FEA;
  constexpr uint24_t Level_Items = 0x0E8008;
  constexpr uint24_t Level_Enemies = 0x0E8023;
  constexpr uint24_t Level_PlayerStart = 0x0E803E;
}

