#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xf4e6;
constexpr uint24_t FX_DATA_BYTES = 723378;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x00AC67;
  constexpr uint24_t SFX_Victory = 0x00AD0B;
  constexpr uint24_t SFX_XPGain = 0x00ADBF;
  constexpr uint24_t SFX_Three_Inc = 0x00ADD3;
  constexpr uint24_t SFX_Three_Dec = 0x00ADEF;
  constexpr uint24_t SFX_PlayerBlip = 0x00AE0B;
  constexpr uint24_t SFX_EnemyBlip = 0x00AE1B;
  constexpr uint24_t SFX_Explosion = 0x00AE2B;
  constexpr uint24_t SFX_DoubleBeep = 0x00AE6F;
  constexpr uint24_t SFX_DoubleBeepDown = 0x00AE7F;
  constexpr uint24_t SFX_Bet1 = 0x00AE8F;
  constexpr uint24_t SFX_Bet2 = 0x00AE97;
  constexpr uint24_t SFX_Bet3 = 0x00AE9F;
  constexpr uint24_t SFX_Bet4 = 0x00AEA7;
  constexpr uint24_t SFX_Bet5 = 0x00AEAF;
  constexpr uint24_t SFX_Bet6 = 0x00AEB7;
  constexpr uint24_t SFX_Click = 0x00AEBF;
  constexpr uint24_t SFX_SmallBlind = 0x00AEC7;
  constexpr uint24_t SFX_BigBlind = 0x00AECF;
  constexpr uint24_t Songs = 0x00AEDF;
  constexpr uint24_t SFXs = 0x00AEE2;
}

namespace Constants
{
  constexpr uint24_t mapCoords = 0x00AF1B;
  constexpr uint24_t TrebochetImgs = 0x00AF53;
  constexpr uint24_t BoatCoords = 0x00AF61;
  constexpr uint24_t StanceImgIdx = 0x00AF81;
  constexpr uint24_t StanceY = 0x00B361;
  constexpr uint24_t xForeground = 0x00B741;
  constexpr uint24_t xMiddleground = 0x00BB21;
  constexpr uint24_t xBackground = 0x00BF01;
  constexpr uint24_t subsititueStance = 0x00C2E1;
  constexpr uint24_t swingyThing_X = 0x00CAA1;
  constexpr uint24_t swingyThing_Y = 0x00CAB1;
  constexpr uint24_t Ball_X = 0x00CAC1;
  constexpr uint24_t Ball_Y = 0x00CAD5;
  constexpr uint24_t BoatMovements = 0x00CAE9;
  constexpr uint24_t SwordLunge_Player = 0x00CB13;
  constexpr uint24_t SwordLunge_Enemy = 0x00CB29;
}

namespace Images
{
  constexpr uint24_t Chakana = 0x00CB3F;
  constexpr uint24_t PPOT = 0x00EF41;
  constexpr uint24_t Sound_Volume_Grey = 0x011F43;
  constexpr uint24_t Sound_Volume_White = 0x012785;
  constexpr uint24_t Sound_Checkbox = 0x012FC7;
  constexpr uint24_t Title_Base = 0x012FD5;
  constexpr uint24_t Title_Options = 0x015FD7;
  constexpr uint24_t Pause = 0x01AC59;
  constexpr uint24_t HUD = 0x01C45B;
  constexpr uint24_t ArrowUpDown = 0x01C5DD;
  constexpr uint24_t Palm1 = 0x01C5EE;
  constexpr uint24_t Palm2 = 0x01CBD8;
  constexpr uint24_t Palm3 = 0x01D0A2;
  constexpr uint24_t Palm4 = 0x01D644;
  constexpr uint24_t Palm5 = 0x01DAEA;
  constexpr uint24_t Palm6 = 0x01DC0C;
  constexpr uint24_t Background = 0x01DD64;
  constexpr uint24_t Background_Above = 0x01E966;
  constexpr uint24_t Player = 0x01EAE8;
  constexpr uint24_t Enemy = 0x0256EA;
  constexpr uint24_t Player_Bounce = 0x029EEC;
  constexpr uint24_t Waves = 0x02A12E;
  constexpr uint24_t Pulse = 0x02AA30;
  constexpr uint24_t Beach = 0x02BC32;
  constexpr uint24_t Beach_LH = 0x02BC4C;
  constexpr uint24_t Boat = 0x02CA5E;
  constexpr uint24_t Boat_Small = 0x02D990;
  constexpr uint24_t Arrow = 0x02DB72;
  constexpr uint24_t InventoryPanel = 0x02DBF8;
  constexpr uint24_t InventoryPanel_Cursor = 0x030BFA;
  constexpr uint24_t Cursor_00 = 0x030D10;
  constexpr uint24_t Cursor_01 = 0x030D48;
  constexpr uint24_t Item_00 = 0x030D80;
  constexpr uint24_t Item_01 = 0x031382;
  constexpr uint24_t Item_02 = 0x031984;
  constexpr uint24_t Item_03 = 0x031EC6;
  constexpr uint24_t Item_04 = 0x0324C8;
  constexpr uint24_t Item_05 = 0x03270A;
  constexpr uint24_t Item_06 = 0x032D0C;
  constexpr uint24_t Item_07 = 0x03330E;
  constexpr uint24_t Item_08 = 0x033910;
  constexpr uint24_t Item_09 = 0x033F12;
  constexpr uint24_t Item_09a = 0x0342D4;
  constexpr uint24_t Item_10 = 0x034312;
  constexpr uint24_t Item_11 = 0x0349D4;
  constexpr uint24_t Item_12 = 0x034FD6;
  constexpr uint24_t Item_13 = 0x038158;
  constexpr uint24_t Item_14 = 0x0385DA;
  constexpr uint24_t Item_15 = 0x0394DC;
  constexpr uint24_t Item_16 = 0x03A3DE;
  constexpr uint24_t Item_17 = 0x03BBE0;
  constexpr uint24_t Item_18 = 0x03C1E2;
  constexpr uint24_t Item_19 = 0x03CAE4;
  constexpr uint24_t Item_20 = 0x03D6E6;
  constexpr uint24_t Item_21 = 0x03DE68;
  constexpr uint24_t Item_21_Action_LH = 0x03E76A;
  constexpr uint24_t Item_21_Action_RH = 0x04206C;
  constexpr uint24_t Map = 0x0467AE;
  constexpr uint24_t Scroll = 0x053FB0;
  constexpr uint24_t Crate_00 = 0x054A32;
  constexpr uint24_t Crate_01 = 0x054AF4;
  constexpr uint24_t Crate_01_02 = 0x054BB6;
  constexpr uint24_t Crate_01_03 = 0x054D38;
  constexpr uint24_t Crate_01_04 = 0x054F7A;
  constexpr uint24_t Crate_02 = 0x05527C;
  constexpr uint24_t Crate_03 = 0x05533E;
  constexpr uint24_t Crate_04 = 0x055400;
  constexpr uint24_t Crate_05 = 0x0554C2;
  constexpr uint24_t Crate_06 = 0x055584;
  constexpr uint24_t Crate_07 = 0x055646;
  constexpr uint24_t Crate_08 = 0x055708;
  constexpr uint24_t Crate_09 = 0x0557CA;
  constexpr uint24_t Crate_10 = 0x05588C;
  constexpr uint24_t Crate_11 = 0x05594E;
  constexpr uint24_t Crate_11a = 0x055A10;
  constexpr uint24_t Crate_12 = 0x055AD2;
  constexpr uint24_t Crate_13 = 0x055B94;
  constexpr uint24_t Crate_14 = 0x055C56;
  constexpr uint24_t Crate_15 = 0x055D18;
  constexpr uint24_t Crate_16 = 0x055DDA;
  constexpr uint24_t Crate_17 = 0x055E9C;
  constexpr uint24_t Crate_18 = 0x055F5E;
  constexpr uint24_t Crate_19 = 0x056020;
  constexpr uint24_t Crate_20 = 0x0560E2;
  constexpr uint24_t Crate_21 = 0x0561A4;
  constexpr uint24_t Crate_22 = 0x056266;
  constexpr uint24_t Crate_23 = 0x056328;
  constexpr uint24_t Crate_24 = 0x0563EA;
  constexpr uint24_t Crate_25 = 0x0564AC;
  constexpr uint24_t Crate_26 = 0x05656E;
  constexpr uint24_t Crate_27 = 0x056630;
  constexpr uint24_t Crate_28 = 0x0566F2;
  constexpr uint24_t Crate_29 = 0x0567B4;
  constexpr uint24_t Crate_30 = 0x056876;
  constexpr uint24_t Crate_31 = 0x056938;
  constexpr uint24_t Crate_32 = 0x0569FA;
  constexpr uint24_t Crate_33 = 0x056CFC;
  constexpr uint24_t Crate_34 = 0x056FFE;
  constexpr uint24_t Crate_35 = 0x057300;
  constexpr uint24_t Crate_36 = 0x057602;
  constexpr uint24_t Crate_37 = 0x0576C4;
  constexpr uint24_t Crate_38 = 0x057786;
  constexpr uint24_t Crate_39 = 0x057848;
  constexpr uint24_t Crate_40 = 0x05844A;
  constexpr uint24_t Crate_41 = 0x05904C;
  constexpr uint24_t Spikes_Top = 0x059C4E;
  constexpr uint24_t Spikes_Bottom = 0x059D10;
  constexpr uint24_t Trebochet_Ball = 0x059DD2;
  constexpr uint24_t Health = 0x05AB54;
  constexpr uint24_t Glint = 0x05B0F6;
  constexpr uint24_t Sword_Wound = 0x05B6F8;
  constexpr uint24_t BoatEnters = 0x05B93A;
  constexpr uint24_t EndOfLevel = 0x0A5D3C;
  constexpr uint24_t PalmImages = 0x0B053E;
  constexpr uint24_t ItemsIndex = 0x0B0556;
  constexpr uint24_t InventoryFrame = 0x0B060D;
}

namespace Levels
{
  constexpr uint24_t Level_00 = 0x0B064A;
  constexpr uint24_t Level_00_Items = 0x0B096A;
  constexpr uint24_t Level_00_Enemies = 0x0B0982;
  constexpr uint24_t Level_00_PlayerStart = 0x0B09A0;
  constexpr uint24_t Levels = 0x0B09A6;
  constexpr uint24_t Level_Items = 0x0B09A9;
  constexpr uint24_t Level_Enemies = 0x0B09AC;
  constexpr uint24_t Level_PlayerStart = 0x0B09AF;
}

